### ISSUE TITLE
Revert to using .NET Standard 1.6 or lower

### ISSUE THREAD

**Issue by aKzenT** [contentful/contentful.net#108]
Hello,

I just noticed that Contentful moved to .NET Standard 2.0 in one of the recent releases.

In my eyes this is a great mistake as it makes Contentful impossible to use in ASP .NET Core 1.1 projects that still target .NET Standard 1.6.

There is no good reason for Contentful to target 2.0, because it still compiles perfectly fine if I switch the dependencies to .NET Standard 1.6 and the corresponding .NET Core 1.1 libraries (e.g. Microsoft.Extensions.Options 1.1.2).

Just to be clear. Projects targetting ASP .NET Core 2.0 can use a .NET Standard 1.6 project perfectly fine and will use the version 2.0 assemblies internally. It doesn't work the other way arround though which is why libraries should intend to target the lowest .NET Standard version they can use.

Is there any chance to support 1.6 again?

I believe I found a bug in the current version which I'm going to report separately when I have a failing unit test. If the fix requires us to update to ASP .NET Core 2.0 though it brings us in a very difficult situation though as we don't have the resources to migrate our (large) website to version 2.0 yet.

Thanks for your consideration!

**Comment by Roblinde** [comment]
Hi

This is of course very unfortunate. One of the main reasons of moving to NetStandard 2.0 was to make the package as inclusive as possible.

I don't have a definite answer right now, but I'll look into this and see what the best approach is.

Thanks.

**Comment by aKzenT** [comment]
To be as inclusive as possible you should target the lowest possible .NET Standard Version.

You can always reference libraries that have a lower .NET Standard version than yourself, but not the other way arround.

So in theory the best things would be to target .NET Standard 1.0, which would mean that even Windows Phone 8 could use your library. However since you have dependencies yourself which require a .NET Standard higher than 1.0, this is not possible.

In your case targetting .NET Standard 1.5 or 1.6 should cause no issues and would allow .NET Framework 4.6.1, .NET Core 1.0, 1.1 and 2.0 to all use your framework.

**Comment by Roblinde** [comment]
You're right, I was mistakenly under the impression that NetStandard 2.0 would be _more_ inclusive than previous versions. The only thing I need to verify is that this change does not break any current applications that run .NET Core 2.0.

I'll investigate and get back to you with information shortly.

**Comment by Roblinde** [comment]
So far I've not found any problem with downgrading at all. If I can't find anything I will try to release a version 1.3 that targets NetStandard 1.4 and 1.6 (for the aspnetcore package) tomorrow.

**Comment by Roblinde** [comment]
I just release version 1.3 to NuGet. It now targets NetStandard 1.4 for the contentful.csharp package and 1.6 for the contentful.aspnetcore package.

As always, thanks for your input. Let me know if it's working as expected.
