### ISSUE TITLE
Entries referenced multiple times in various nestings are sometimes resolved to null

### ISSUE THREAD

**Issue by aKzenT** [contentful/contentful.net#109]
If you have a structure like this:

```
RootEntry
- NestedItem
-- SharedItem
- SharedItem
```

Where RootEntry, NestedItem and SharedItem refer to different entries, then the SharedItem is only resolved correctly the first time it is used.

Failing test case follows as pull request.

**Comment by aKzenT** [comment]
It seems to be the case that this happens only when NestedItem is not mapped to a property in the class. My guess is that deserialization skips the property and corresponding JSON completely and cannot resolve the following $ref.

**Comment by Roblinde** [comment]
Thanks for the contribution!

A property was introduced in version `0.13.10-beta` that should take care of this situation.

If you set `ResolveEntriesSelectively` on your ContentfulClient it should hopefully only serialize properties that are in use. It's an expensive operation as it currently includes a bit of reflection which is why it's not on by default.

It can also be set through the `ContentfulOptions` if you'd rather have it on for your entire solution.

Hope this helps!

Best

Robert

**Comment by aKzenT** [comment]
Ah, that's good to know. It makes sense that JSON .NET can't handle this as it cannot know the type if there is no matching property.

However I think there might be a problem with the current version if you use dynamically resolved content types. The type of the property in this case would be the interface and not the actual content type used later during deserialization.

**Comment by Roblinde** [comment]
Ah yeah, that might be the case. I'll have a look at that.

**Comment by Roblinde** [comment]
A fix for resolving even with dynamically resolved content types is now available. It's still in NetStandard 2.0 though. We will continue that discussion in the other issue 😄

**Comment by aKzenT** [comment]
That's nice. I will test as soon as we have a solution for .NET Standard 1.6. In the meantime I tried looking for better solutions than using reflection to scan the properties. One interesting thing I found was using the [JsonExtensionData] Attribute. Basically it's a way to tell JSON.NET to transfer all properties it doesn't understand to a dictionary inside the object. So you can declare it like:

```
	[JsonExtensionData]
	private IDictionary<string, object> ExtensionData;
```

This will solve some of the issues, but only if the $type is present in the JSON and it doesn't seem to work with lists for some reason. Just wanted to note it in case someone has similar issues. I also raised a ticket on the JSON.NET project to provide better $id/$ref support, but I'm not sure this will result in anything.

**Comment by Roblinde** [comment]
Interesting, it could be an alternative. Could you link to the JSON.NET issue here as well. Just for future reference.

**Comment by aKzenT** [comment]
Sorry for the late response. The update package solved our problems. Thanks a lot!

The issue I created for JSON.NET is https://github.com/JamesNK/Newtonsoft.Json/issues/1434

So far however there has not been any response from the developer unfortunately.

Having a good way to solve this without having to manually scan properties and using Reflection would be very nice.

**Comment by Roblinde** [comment]
Fantastic!

Yeah, I agree... it's not great to have to resort to reflection here. It feels error prone and slow.
