### ISSUE TITLE
Multi-tenancy space id support

### ISSUE THREAD

**Issue by stephenlautier** [contentful/contentful.net#129]
Hi,

We are building an application which will support multi tenancy e.g. having multiple brands within the same code concurrently, and we are planning to have space per brand.

Currently by peeking a little bit into your code it seems like it is possible by manually creating/managing multiple instances of the `ContentfulClient`, however most probably an easier approach would be if we can pass the `SpaceId` with the `QueryBuilder` which currently its not supported. 

Is it something you can implement or open for PR to pass the space id as part of the `QueryBuilder`?
Thanks.

**Comment by Roblinde** [comment]
Hi Stephen and thanks for your contribution!

I think a better approach in this case would be to add that as an optional parameter for each operation, much like is the case with the `ContentfulManagementClient`. But as you said the intention was to use one client per case, but since the managementclient operates over multiple spaces potentially it was necessary to add that possibility there. Either that or just exposing a property on the client that can be set might be even simpler.

Another approach that you might find suitable would be to have the dependency injection mechanism create a client with the correct space defined.

I'm thinking something along the lines of:

```
services.AddTransient<IContentfulClient, ContentfulClient>((ip) => {
                var client = ip.GetService<HttpClient>();
                var options = ip.GetService<IOptions<ContentfulOptions>>().Value;
               
              options.SpaceId = YourMethodForSelectingTheCorrectSpaceId();
               
                var contentfulClient = new ContentfulClient(client,
                    options);
                return contentfulClient;
            });
```

You could also considering creating some kind of factory service that creates the client:

```
public interface IContentfulClientFactory  {
     IContentfulClient GetClient();
}

public class ContentfulClientFactory : IContentfulClientFactory {

     private ContentfulOptions _options;
     private readonly HttpClient_client;

     public ContentfulOptionsManager(IOptions<ContentfulOptions> options, HttpClient client)
        {
            _options = options.Value;
            _client = accessor;
        }

    public IContentfulClient GetClient() {
         _options.SpaceId = SomeMethodForFiguringOutWhichSpaceIdToSetBasedOnApplicationState();
        return new ContentfulClient(_client, _options);
    }
}

// And then in startup.cs

services.AddTransient<IContentfulClientFactory, ContentfulClientFactory>();
```

And then simply consume that class instead of the `IContentfulClient` directly. I think this would result in a clean and testable architecture.

What are your thoughts on this?

Best
Robert

**Comment by stephenlautier** [comment]
@Roblinde thanks for your reply!

I believe having the factory might be a good solution I quite like it.
That said adding the option to the `QueryBuilder` it would be a little be more flexible and get more support for it out of the box.

**Comment by Roblinde** [comment]
I agree overriding the SpaceId property might not be such a bad idea. It offers some flexibility. I don't think `QueryBuilder` is the right place for it though. The `QueryBuilder` is used to append the query string to the call and maps directly to the options available in the Contentful API. I feel like adding a space option here would pollute its usage and add some unecessary complexity when parsing it.

What do you think of just being able to set the `SpaceId` directly on the `IContentfulClient`?

Something like:

```
_client.SpaceId = "OverridenSpaceId";
await _client.GetEntries();
```

**Comment by stephenlautier** [comment]
That won't be a good idea, due to concurrency they would override each other and it will cause problems, so it has to be scoped.
I was seeing it more to be passed in the `QueryBuilder` since it gives kind of a fluent API and also not too pollute methods with too many parameters/overrides of each method. Personally, as a consumer, I wouldn't care whether the `QueryBuilder` sets them as query strings or path, but maybe how its implemented or how its designed to work it makes a difference.

**Comment by Roblinde** [comment]
Stephen, I'm sorry, I'm being stupid 😊 

You can't just change your space id on the client. The access token is tied to a specific space, so to be able to call a different space you would also have to update your access token.

I think the factory pattern I suggested above is the best approach to this. Then the factory can create a client with all the appropriate configuration and pass this back to the application.

Sorry again for the confusion.

**Comment by stephenlautier** [comment]
Don't worry :). Thats a good point! Yes, most probably the factory approach would be the best. We will be needing this in about 2 more months but I wanted to check here first. 

I can close this issue for now. Thanks!

**Comment by Roblinde** [comment]
Thanks and best of luck.

Just let me know if you have any further questions.
