### ISSUE TITLE
Make Delivery and Preview requests from single client

### ISSUE THREAD

**Issue by sugarjig** [contentful/contentful.net#131]
In our application we would like to support both preview and non-preview content, allowing it to change at request time. Because `ContentfulClient` takes a boolean `usePreviewApi`, we have to instantiate two `ContentfulClients` in order to get this to work. Is it possible to add support for the Preview API at runtime, via method parameters or some other mechanism?

**Comment by Roblinde** [comment]
Hi Sam and thanks for your contribution!

Since the SDK uses the options pattern it's actually not that simple to change the configuration at runtime, but exposing 

What I suggest in situations like this is to use a factory pattern to instantiate the options. Something along these lines:

```
    public interface IContentfulOptionsManager
    {
        /// <summary>
        /// Gets the currently configured <see cref="ContentfulOptions"/>.
        /// </summary>
        ContentfulOptions Options
        {
            get;
        }
    }

public class ContentfulOptionsManager : IContentfulOptionsManager
    {
        private ContentfulOptions _options;
        private readonly IHttpContextAccessor _accessor;

        public ContentfulOptionsManager(IOptions<ContentfulOptions> options, IHttpContextAccessor accessor)
        {
            _options = options.Value;
            _accessor = accessor;
        }

        public ContentfulOptions Options {
            get {
                var sessionString = _accessor.HttpContext.Session.GetString(nameof(ContentfulOptions));

                if (!string.IsNullOrEmpty(sessionString))
                {
                    return JsonConvert.DeserializeObject<ContentfulOptions>(sessionString);
                }
                return _options;
            }
        }
    }
```

and then setting up your startup.cs something like this:

```
            services.AddSingleton<IContentfulOptionsManager, ContentfulOptionsManager>();
            services.AddTransient<IContentfulClient, ContentfulClient>((ip) => {
                var client = ip.GetService<HttpClient>();
                var options = ip.GetService<IContentfulOptionsManager>().Options;
                var contentfulClient = new ContentfulClient(client,
                    options);
                return contentfulClient;
            });
```

You might not want to use session but rather some other mechanism, this is just an example implementation.

I hope this helps!

**Comment by sugarjig** [comment]
Thanks for the suggestion! We'll take a look at this.

**Comment by Roblinde** [comment]
No problem, just let me know if you need any further assistance.

**Comment by Roblinde** [comment]
Hi Sam!

Just wanted to check how you're getting along? Was the factory pattern approach suggested above a good fit for you?

**Comment by sugarjig** [comment]
Thanks for following up! And sorry for the delayed response. We're exploring this solution and another where we inject 2 Contentful clients into a service that is registered as a singleton. In the latter, we avoid instantiating a client every time it is used (if we're understanding it correctly).

**Comment by Roblinde** [comment]
No problem at all.

Having 2 clients should be fine, but it should be very cheap to instantiate one as well. 

I'll close this issue for now, but feel free to reach out again if I can help you with anything else.
