### ISSUE TITLE
ContentfulManagementClient.CreateExtension method does not appear to communicate with API correctly

### ISSUE THREAD

**Issue by lance-h** [contentful/contentful.net#142]
I'm attempting to create a new UI Extension using the SDK with the following code:

```
await ManagementClient.CreateExtension(new UiExtension
{
  FieldTypes = new List<string> {"Object"},
  Name = "JSON Form Editor",
  SystemProperties = new SystemProperties {Id = "jsonFormEditor"},
  Src = "http://localhost:60258/contentful/editor-extensions/test/index.html"
});
```

This code compiles correctly, however the API response indicates failure when running.

Request:

```
POST https://api.contentful.com/spaces/n9r0opbftsp6/extensions HTTP/1.1
Connection: Keep-Alive
Content-Type: application/vnd.contentful.management.v1+json; charset=utf-8
Authorization: Bearer xxxx
X-Contentful-User-Agent: sdk contentful.csharp/2.1.4; platform .net; os Windows;
Content-Length: 180
Host: api.contentful.com

{"extension":{"src":"http://localhost:60258/contentful/editor-extensions/test/index.html","name":"JSON Form Editor","fieldTypes":[{"type":"Object"}],"srcDoc":null,"sidebar":false}}
```

Response:

```
HTTP/1.1 422 Unprocessable Entity
***Headers removed for brevity***

{
  "sys": {
    "type": "Error",
    "id": "ValidationFailed"
  },
  "message": "Validation error",
  "details": {
    "errors": [
      {
        "name": "unexpected",
        "details": "The property \"srcDoc\" is not expected",
        "path": [
          "extension",
          "srcDoc"
        ]
      }
    ]
  },
  "requestId": "04c4be0853982f218a3eaf8382834425"
}

```

At first glance I would assume that this is occurring because srcDoc is being included in the request even though it's value is null. As an attempted workaround I tried to ensure that Null values were not serialized with the following code immediately prior to the CreateExtension call:

```
ManagementClient.SerializerSettings.NullValueHandling = NullValueHandling.Ignore;
```

This had no effect.

I also tried a few different permutations, including setting SrcDoc and leaving Src empty, and setting both to non-null strings - none worked.

Any thoughts on this?

**Comment by lance-h** [comment]
Actually - it may be a casing issue. It looks like srcDoc should actually be srcdoc.

**Comment by Roblinde** [comment]
Hi Lance!

Thanks for reporting this. I'll have a look.

**Comment by Roblinde** [comment]
Thanks for finding this Lance. I will soon release a fix for this in version 2.2.1 once this PR is merged: https://github.com/contentful/contentful.net/pull/143

**Comment by Roblinde** [comment]
The new version has now been released. Just let me know if something doesn't work as expected.

**Comment by lance-h** [comment]
Thanks @Roblinde !
