### ISSUE TITLE
Make ImageUrlBuilder/TagHelper smarter

### ISSUE THREAD

**Issue by aKzenT** [contentful/contentful.net#149]
When setting quality, width, or progressive property on the tag helper or the ImageUrlBuilder, these are used in the query string even if the parameters do not match the requested content type (e.g. jpg-quality for png).

While the asset can still be loaded, it will make the browser think that the asset is really different from the same asset with other query-strings causing cache misses.

**Comment by Roblinde** [comment]
Would you suggest to just remove the superfluous parameters? For example if you've set progressive for a png the progressive property just gets ignored?

**Comment by Roblinde** [comment]
I'll look into it, shouldn't be too much work, it feels like it's just really a few parameters that are image format specific.

**Comment by aKzenT** [comment]
Agreed. One challenge could be to handle srcset in the tag helper in case of SVG... I'm not sure what the best way would be. We could just leave the entries in the srcset, even if they have the same URL. Browser shouldn't care. Or try something more intelligent, like not outputting srcset at all if the parent and all children have format SVG and refer to the same asset.

**Comment by Roblinde** [comment]
Lets start by simply making sure that progressive and jpg quality are only outputted if you specifically request a jpg format (or omit format, in that case it's up to you to make sure it's a jpg asset).

Once we have that we can evaluate whether or not we need some extra logic in the taghelpers.

**Comment by Roblinde** [comment]
This should now be available in version 3.3.1

Try it out and see if it's enough, otherwise we can discuss further improvements of the taghelper as well.

Cheers!

**Comment by aKzenT** [comment]
Hey, thanks for the rapid update. I tested it, but I think there is something essential missing. The URL cleanup only works if you explicitly request another format than the original one.

However what we actually need is that whenever the format of the image is not JPG (original format or changed one), than the jpg-parameters should not be sent.

This might require changes in the asset tag helper itself as the content type is not known in the query builder.

**Comment by Roblinde** [comment]
Ah, yeah. I figured this might be the case. Yeah, then the logic needs to live in the taghelper... I'll look into that tomorrow.

**Comment by Roblinde** [comment]
Would love if you tried it out now. I've refactored the logic slightly for the taghelpers. Should do the trick!

**Comment by aKzenT** [comment]
See comment in PR

**Comment by Roblinde** [comment]
Version 3.3.3 should be available shortly and fix this. Give it a try and holler if I've missed something again.

**Comment by aKzenT** [comment]
Thanks for the rapid response and release! Looks good as far as I can tell. I will update if I notice anything else.
