### ISSUE TITLE
Publish NuGet packages using Org instead of User account.

### ISSUE THREAD

**Issue by olegburov** [contentful/contentful.net#157]
The [nuget.org](https://www.nuget.org/) now supports [Organization accounts](https://blog.nuget.org/20180417/organizations-on-nuget-org.html). Please publish the NuGet packages `contentful.csharp`, `contentful.aspnetcore` etc. using Org accounts instead of User one.

For more information see here:
- https://docs.microsoft.com/en-us/nuget/reference/organizations-on-nuget-org

**Comment by Roblinde** [comment]
Hi Oleg!

Thanks for the suggestion, I'll look into this when I get an opportunity.

**Comment by olegburov** [comment]
@Roblinde you're welcome!

You might also want to reserve ID `Contentful` on the nuget.org, see details here: 

- https://docs.microsoft.com/en-us/nuget/reference/id-prefix-reservation

**Comment by Roblinde** [comment]
This is now updated. The reservation process for Contentful is also in progress.
