### ISSUE TITLE
Verify Contentful org account at GitHub.

### ISSUE THREAD

**Issue by olegburov** [contentful/contentful.net#160]
I don't believe this is the best repository in Contentful org account, but I still want to try 😃

Would be nice to verify Contentful org account at GitHub. See here for details:
https://help.github.com/articles/verifying-your-organization-s-domain/

**Comment by Roblinde** [comment]
Probably not the right place, but I will forward the suggestion internally 😄 

Thanks!

**Comment by felipecoe** [comment]
Hi @olegburov , thanks for the advice. The funny thing is that I was doing this yesterday morning, so our minds must have been syncing :) DNS took a while and our account is now verified.
Cheers

**Comment by olegburov** [comment]
@felipecoe Oh wow! 🤗That was fast. Thanks for the update.
