### ISSUE TITLE
Using `Document` to serialize new `Rich Text` throwing exception from Client

### ISSUE THREAD

**Issue by pfrendo** [contentful/contentful.net#168]
Using `Document` to serialize new `Rich Text` throwing `Object not set to an instance of an object` exception from client when an entry is embedded.

![image](https://user-images.githubusercontent.com/13260474/49992077-5237fe00-ff83-11e8-87b8-a3a10a5c34ca.png)

![image](https://user-images.githubusercontent.com/13260474/49992020-2a489a80-ff83-11e8-9f8d-a250d7fd5876.png)

**Comment by Roblinde** [comment]
When you have entries embedded you need to instruct the deserializer how to handle the new object introduced. If you follow the steps explained here: https://www.contentful.com/developers/docs/net/tutorials/rich-text/#working-with-custom-node-types

Does that help alleviate the problem?

**Comment by Roblinde** [comment]
I just got a similar ticket through our ticket system which I responded to. I believe I need to add a more descriptive error message to this case.

Anyway, here's the solution 😄

When working with embedded entries in a rich text field it's important to instruct the deserialization engine which class to deserialize your entry into. This is done by creating a custom content resolver class. Here's an example:

```
public class EntityResolver : IContentTypeResolver
    {
        public Dictionary<string, Type> _types = new Dictionary<string, Type>()
        {
            { "person", typeof(Person) }
        };

        public Type Resolve(string contentTypeId)
        {
            return _types.TryGetValue(contentTypeId, out var type) ? type : null;
        }
    }
```

This class maps a content type id, for example `"person"`, to a strongly typed class, for example `Person`.

You then set this content type resolver on your client before making a call to fetch entries:

```
_client.ContentTypeResolver = new EntityResolver();
var entries = await _client.GetEntries<SomeModel>();
```

To be able to use a custom class like this as part of a rich text structure, the class must also implement `IContent`, which is a simple marker interface for rich text deserialization.

```
public class Person : IContent
{ 
public string Name { get; set; } 
}
```

Remember, for every new content typeyou wish to embed as part of a structure like this, you need to add it to the resolver and make sure it implements `IContent`.

I will add to the backlog to make sure the error thrown in this circumstance is more descriptive than a plain old null reference.

Let me know if this helps you solve the problem.

**Comment by Roblinde** [comment]
@pfrendo I hope this helped you move forward. 

Since I haven't heard anything back in a while I'll go ahead and close this.
