### ISSUE TITLE
Get Entry<T> respone have no Media Field

### ISSUE THREAD

**Issue by phanlh3050** [contentful/contentful.net#179]
I use GetEntries< Project >(string builder): I Got all entries with all fields, include the media field and each media element has File.url value, which i need
But
When I Use 
GetEntry< Project >(“Entry_id”) to get specific entry: I got respone like GetEntries<Project>(String builder) exclude 
Media field
Element in mèdiafield just has sys.id , others are null
I make sure that all my entries have no null field

**Comment by Roblinde** [comment]
The GetEntry method does not resolve references as per the API specification https://www.contentful.com/developers/docs/references/content-delivery-api/#/reference/links

I suggest using `GetEntries<Project>("?sys.id=ID")` or the `QueryBuilder` equivalent.

**Comment by boncyrus** [comment]
> The GetEntry method does not resolve references as per the API specification https://www.contentful.com/developers/docs/references/content-delivery-api/#/reference/links
> 
> I suggest using `GetEntries<Project>("?sys.id=ID")` or the `QueryBuilder` equivalent.

Not sure if I'm doing it correctly, what I did was 
`var builder = QueryBuilder<Deals>.New.ContentTypeIs("contentTypeId").Include(10);
var entries = await client.GetEntries(builder);`

When I access `entries.Items`, some properties are null for some items, while other items are Deserialized correctly.

**Comment by Roblinde** [comment]
@boncyrus `GetEntries` is the correct way to fetch the items. If you have multiple items referencing the same content but not being part of the response you can se the `ResolverEntriesSelectively` property to true on the client.

```
var builder = QueryBuilder<Deals>.New.ContentTypeIs("contentTypeId").Include(10);
client.ResolveEntriesSelectively = true;
var entries = await client.GetEntries(builder);
```

**Comment by boncyrus** [comment]
@Roblinde Can I talk to you via call or something like that? I'm still facing the same issue even though I already set `ResolveEntriesSelectively = true`

**Comment by bonmacalindong** [comment]
@Roblinde I've managed to get it to work. `ResolveEntriesSelectively = true` did the trick. Just disregard my previous reply :)
