### ISSUE TITLE
Is it possible to use the select operator?

### ISSUE THREAD

**Issue by jerriep** [contentful/contentful.net#182]
Does the Contentful .NET SDK support the [select operator](https://www.contentful.com/developers/docs/references/content-delivery-api/#/reference/search-parameters/select-operator) available in the Content Delivery API?

I cannot see any way to do this on the `QueryBuilder<>`

**Comment by jerriep** [comment]
Just pinging again about this one. Is anyone still working on this library? 

cc @Roblinde

**Comment by faberyx** [comment]
Would be interesting to know, couldn't find any select in the documentation

**Comment by Roblinde** [comment]
Hello, yes it is possible. I answered the question in the community slack a while back, but I'll add the answer here too for posterity. Unfortunately I still can't close issues 😛 

The select operator is not directly supported through the querybuilder, however the querybuilder is just a glorified stringbuilder you can make a call including the select operator like this:

```csharp
var queryString = QueryBuilder<YourClass>.New.ContentTypeIs("<content_type_id>").Build();
var entries = await client.GetEntries(queryString + "&select=fields.productName");
```

**Comment by faberyx** [comment]
works perfectly! thanks  a lot!!

**Comment by Roblinde** [comment]
Great to hear!

Now if only I could close issues...

**Comment by Roblinde** [comment]
Thanks @jerriep
