### ISSUE TITLE
Custom ContentRenderer for HtmlRenderer 

### ISSUE THREAD

**Issue by andymac4182** [contentful/contentful.net#193]
Hi,

I would like to add a new ContentRenderer for my space that allows the user to reference content and the HtmlRenderer generate a HTML Hyperlink to that content. I can do this by modifying the library and using a local copy to expose the `_contentRendererCollection`  https://github.com/contentful/contentful.net/blob/master/Contentful.Core/Models/Authoring.cs#L15 field to be able to pass it back into the new renderer. Is there a better way to do this?

Cheers,
Andrew

**Comment by Roblinde** [comment]
Hi @andymac4182 

Yes, the `HtmlRenderer` exposes a method `AddRenderer` that you can use to inject a custom renderer into the pipeline. You can use the `Order ` property of your custom renderer to control in which order the renderers are run.

Hope this helps.

**Comment by andymac4182** [comment]
@Roblinde I saw that. I cloned the `HyperlinkRenderer` which requires access to the collection so it can render subcontent. I would like to do the same so I can just handle the part I need to.

**Comment by Roblinde** [comment]
Ah, sorry I misunderstood. Let me have another look.

**Comment by Roblinde** [comment]
Hmm, no sorry, there's no way to do this currently. I think the best way right now would be to create your own renderer. You could copy `HtmlRenderer` in it's entirety (it's just 60 lines of code) and just substitute the HyperlinkRenderer with your own implementation. 

However, maybe there should be a way to expose the `_contentRendererCollection` to renderers, just need to figure out how that API would look...

**Comment by andymac4182** [comment]
Thanks. I will copy the HtmlRenderer for now 👍  Thanks for the super fast replies.

**Comment by Roblinde** [comment]
No problems, I'll close this for now while I consider whether  `_contentRendererCollection` should be exposed or not.
