### ISSUE TITLE
Nested and Multipe reference Deserialization issue

### ISSUE THREAD

**Issue by vibhorkaushik** [contentful/contentful.net#198]
Hi,
My project design is given below where I have created three contentModel "contentA", "content B" and "PageContent".

- content A

   1. title
   2. Name

- content B

   1. Title
   2. Image

- PageContent

   1. Title
   2. Slug
   3. Modules (List of content A and content B)

How can I deserialize Page content response in .net class when I get an entry by its slug?

How my model for PageContent should look like?

**Comment by Roblinde** [comment]
Hi @vibhorkaushik 

Just create a regular c# class for your PageContent something like:

`public class PageContent {
public string Title {get; set;}
public string Slug {get;set;}
public List<IContentAnB> {get; set;}
}`

Make sure you create classes for Content A and B and make them implement the IContentAnB interface and use a ContentTypeResolver to instruct the serialization engine how to deserialize classes of type A and B.  Here's a handy tutorial for implementing a resolver: https://www.contentful.com/developers/docs/net/tutorials/using-net-cda-sdk/#get-entries-of-multiple-types-or-by-interface

**Comment by vibhorkaushik** [comment]
Thanks for the reply but problem is still there with deserialization. Here is my code

`namespace` Hypergate.Contentful.Areas.Contentful.Models
{
    public class PageModel
    {
        public string Name { get; set; }
        public string Slug { get; set; }
        public List<Module> Modules { get; set; }
    }
    public class PopUpLead
    {
        public string Title { get; set; }
    }
    public class HTMLCallout
    {
        public string Title { get; set; }
    }
    public class Module
    {
        public PopUpLead popUpLead { get; set; }
        public HTMLCallout htmlCallout { get; set; }
    }

    public class EntityResolver : IContentTypeResolver
    {
        public Dictionary<string, Type> _types = new Dictionary<string, Type>()
        {
            { "componentPopUpLead", typeof(PopUpLead) },
            { "componentHtmlCallout", typeof(HTMLCallout) },
        };

        public Type Resolve(string contentTypeId)
        {
            return _types.TryGetValue(contentTypeId, out var type) ? type : null;
        }
    }
}

Here I am calling contentful
        public ContentfulClient GetServiceClient()
        {
            var httpClient = new HttpClient();
            var options = new ContentfulOptions
            {
                ManagementApiKey = _appSettings.RedesignContentfulOptions.ManagementApiKey,
                SpaceId = _appSettings.RedesignContentfulOptions.SpaceId,
                Environment = _appSettings.RedesignContentfulOptions.Environment,
                DeliveryApiKey = _appSettings.RedesignContentfulOptions.DeliveryApiKey

            };
            var client = new ContentfulClient(httpClient, options);
            client.ContentTypeResolver = new 
            Hypergate.Contentful.Areas.Contentful.Models.EntityResolver();
            return client;
        }

        public async Task<ContentfulCollection<T>> GetContentAndChildByContentType<T>(string 
         contentType, string fieldName, string fieldValue)
        {
            var entry = new ContentfulCollection<T>();
            var builder = 
            QueryBuilder<T>.New.Include(6).ContentTypeIs(contentType).FieldEquals(fieldName, 
             fieldValue);
            entry = await GetServiceClient().GetEntries(builder);
            return entry;
        }
`
Method called:
var entry = await obj.GetContentAndChildByContentType<PageModel>("pages", "fields.slug", slug);

But getting an exception for
 
![image](https://user-images.githubusercontent.com/52735723/79864215-b92aba00-83f6-11ea-9ae7-2e1bfaeb4af3.png)

**Comment by Roblinde** [comment]
Hi

You have a list `public List<Module> Modules { get; set; }` but you're trying to fill it with `HtmlCallout` and `PopUpLead`

Let them instead implement a common interface such as `IModule` and make your list `public List<IModule> Modules { get; set; }`

Make sure both `HtmlCallout` and `PopUpLead` implement this interface.

**Comment by vibhorkaushik** [comment]
Thank You so much,
It's working fine now and nested reference of the same type has also resolved...
Thanks a lot again.!!

**Comment by vibhorkaushik** [comment]
Hi,
Sorry for bothering you again but now the problem is with $ref in response when I am trying to deserialize it's returning null in response.
I am getting List<Imodules> in response where IModule could be of any type.
it's containing object A, object B, object A
but I am deserializing it's converting only the first two objects except for the third one as it is of $ref type.
code sample is:
 var _jsonSettings = new JsonSerializerSettings()
            {
                TypeNameHandling = TypeNameHandling.Auto,
                ConstructorHandling = ConstructorHandling.AllowNonPublicDefaultConstructor,
                PreserveReferencesHandling = PreserveReferencesHandling.All,
                ObjectCreationHandling = ObjectCreationHandling.Auto
            };

            ContentfulServicesHelper obj = new ContentfulServicesHelper(_appSettings);
            var entry = await obj.GetContentAndChildByContentType<dynamic>("pages", "fields.slug", slug, _appSettings.SitecoreMigrationContentfulOptions, levelInclude);
            var data = JsonConvert.DeserializeObject<PageModel>(JsonConvert.SerializeObject(entry.Items.FirstOrDefault(), Formatting.Indented, _jsonSettings)
                , _jsonSettings);

**Comment by Roblinde** [comment]
Hi @vibhorkaushik 
Have you seen this blog post: https://robertlinde.se/posts/why-is-my-item-null-contentful-net/

It sounds like this could be your issue. Hopefully just setting `ResolveEntriesSelectively=true` should solve it.

**Comment by vibhorkaushik** [comment]
Hi,
After adding "ResolveEntriesSelectively = true" in contentfulOptions. 
$ref problem has been resolved but a new one starts coming in picture that all nested object not getting deserialized. and if I am removing this then the nested object problem gets resolved but $ref start coming.

**Comment by Roblinde** [comment]
Hmm, do you have the same content type deserialized into multiple types? Could you describe the kind of nested objects are not getting deserialized?

**Comment by vibhorkaushik** [comment]
This is the structure of the model. And I am trying to deserialize the JSON into PageModel where I can have a list of modules and list of LoggedInModules.
and both can have multiple objects of PopUpLeadModel. So while deserializing I got modules and loggedInmodules but getting the only id of all nested objects.
And if not using "ResolveEntriesSelectively = true" then nested object get deserialized but all objects with $ref start returning null.

    public class PageModel
    {
        public string Name { get; set; }
        public string Slug { get; set; }
        [JsonProperty(TypeNameHandling = TypeNameHandling.Objects)]
        public List<IModule> Modules { get; set; }
        public string Classes { get; set; }
        public Metadata Metadata { get; set; }
        public Analytics Analytics { get; set; }
        public string Title { get; set; }
        [JsonProperty(TypeNameHandling = TypeNameHandling.Objects)]
        public List<IModule> LoggedInModules { get; set; }

    }

    [JsonConverter(typeof(ContentfulJsonConverter))]
    public interface IModule
    {

    }

    public class PopUpLeadModel : ContentfulBaseModel, IModule
    {
        public LeadError Error { get; set; }
        public LeadScheduleAVisitThankyou ScheduleAVisitThankYou { get; set; }
        public LeadStep1 Step1 { get; set; }
        public LeadStep2 Step2 { get; set; }
        public LeadThankyou ThankYou { get; set; }
        public string Classes { get; set; }
        public string DataTitle { get; set; }
        public bool FullWidth { get; set; }
        public GDPROptIn GDPROptIn { get; set; }
        public LeadSMSCopy LeadSMSCopy { get; set; }
    }

    public class LeadStep1 : ContentfulBaseModel
    {
        public string ActivationCode { get; set; }
        public string AlternateTime { get; set; }
        public string ButtonCaption { get; set; }
        public bool CaptchaRequired { get; set; }
        public string Description { get; set; }
        public string FieldsRequired { get; set; }
        public string Label { get; set; }
    }

    public class LeadStep2 : ContentfulBaseModel
    {
        public string AppointmentDescription { get; set; }
        public string AppointmentTitle { get; set; }
        public string ButtonCaption { get; set; }
        public string Description { get; set; }
        public string Label { get; set; }
    }

    public class LeadThankyou : ContentfulBaseModel
    {
        public string ButtonCaption { get; set; }
        public string Description { get; set; }
        public string Label { get; set; }
    }

    public class LeadError : ContentfulBaseModel
    {
        public string Description { get; set; }
        public string Title { get; set; }
        public string Label { get; set; }
        public List<object> Step1 { get; set; }

    }

    public class LeadScheduleAVisitThankyou : ContentfulBaseModel
    {
        public string AppointmentDetailsCaption { get; set; }
        public string ButtonCaption { get; set; }
        public string Description { get; set; }
        public string Label { get; set; }
    }

    public class GDPROptIn : ContentfulBaseModel
    {
        public string FacilityIds { get; set; }
        public string Description { get; set; }
    }

    public class LeadSMSCopy : ContentfulBaseModel
    {
        public string Title { get; set; }
        public string Message { get; set; }
        public string ToolTip { get; set; }
        public string PilotFacilities { get; set; }

    }

**Comment by Roblinde** [comment]
This looks fine on a quick glance. Do you have the Includes set to a high enough value?

**Comment by vibhorkaushik** [comment]
How many it should be.  for now 6 is there

**Comment by vibhorkaushik** [comment]
we don't have that much complex object.
pageModel
   --List<IModule> Modules
          --HTMLCalloutModel
          --PopUpLeadModel
                 --LeadErrorModel
                 --step1model
and same structure will be for  LoggedinModules.

**Comment by vibhorkaushik** [comment]
This is how It get deserialized
![image](https://user-images.githubusercontent.com/52735723/81046802-c5bf1000-8ed6-11ea-96d6-cc3bac38a408.png)

**Comment by Roblinde** [comment]
aah, but you're turning everything into `dynamic`, you should use a strong type like IModule or something and it should work better for you. You can't use `dynamic` and `ResolveEntriesSelectively` together as there's no propertys on `dynamic` to reflect.

**Comment by vibhorkaushik** [comment]
We can't provide a strong type class here as we are using this function in our microservice which will return you a JSON and then we deserialize this in our other service where we created all these models. If we don't use ResolveEntriesSelectively then the only problem we face is with $ref. Is there any way where we can get object except $ref.

**Comment by Roblinde** [comment]
Then you would have to resolve the $ref yourself I'm afraid. But why can't you use a strong type, then turn that into JSON and return that from your microservice?

**Comment by vibhorkaushik** [comment]
I tried to put a strong type class but still getting null for the repeated object in response.
![image](https://user-images.githubusercontent.com/52735723/81057356-e5136880-8ee9-11ea-92e5-9ba2d4485438.png)

**Comment by Roblinde** [comment]
This looks good, the two null entries, do they implement IModule and do they have content types present in the ContentTypeResolver?

**Comment by vibhorkaushik** [comment]
Yes, Both Modules and LoggedIn modules are a list of IModules and both have the same kind of objects.
And for LoggedInModules we are getting $ref for attached objects. That's the reason it's not deserializing.

**Comment by Roblinde** [comment]
No, the $ref is just a pointer to another object. This means the object has already been deserialized elsewhere in the structure, the question is why it can't resolve it. Do you have `ResolveEntriesSelectively=true` in this example?

**Comment by vibhorkaushik** [comment]
If I use ResolveEntriesSelectively=true then no object gets deserialized.
Is there any way where I can fetch only selected fields from contentful?
var builder = QueryBuilder<T>.New.Include(levelInclude).ContentTypeIs(contentType).FieldEquals(fieldName, fieldValue);

This is my query. If I can fetch only selected fields, It may resolve this reference issue.

**Comment by Roblinde** [comment]
Yes you can, by using the "select" operator. You will have to append it manually to the query string. https://www.contentful.com/developers/docs/references/content-delivery-api/#/reference/search-parameters/select-operator/query-entries/console/dot-net

**Comment by vibhorkaushik** [comment]
Getting the selected fields but now the problem is to deserialize it
Here is the response what I am getting
![image](https://user-images.githubusercontent.com/52735723/81677590-b6a80700-946e-11ea-920d-8fc0ec7c8df1.png)

**Comment by Roblinde** [comment]
If you're using dynamic I'm afraid you have to resolve the references manually as there're no properties to resolve to.

**Comment by vibhorkaushik** [comment]
I tried with strongly typed class but still, it's not resolving references and getting null for a reference type.

**Comment by Roblinde** [comment]
hmm, this sounds very strange. Could you share the classes that you are using when you're not using dynamic? Perhaps I can spot something.

**Comment by vibhorkaushik** [comment]
https://github.com/contentful/contentful.net/issues/198#issuecomment-623884344
This is the complete structure and I am referencing PageModel on the place of dynamic

**Comment by Roblinde** [comment]
Allright, and what does the JsonConverter `ContentfulJsonConverter` for IModule look like. You shouldn't need one of those in most cases. The ContentTypeResolver should be enough. What does the ContentTypeResolver look like?

**Comment by vibhorkaushik** [comment]
public class ContentfulJsonConverter : JsonConverter
    {
        public override bool CanWrite => false;
        public override bool CanRead => true;
        public override bool CanConvert(Type objectType)
        {
            return objectType == typeof(IModule);
        }
        public override void WriteJson(JsonWriter writer,
            object value, JsonSerializer serializer)
        {
            throw new InvalidOperationException("Use default serialization.");
        }

        public override object ReadJson(JsonReader reader,
            Type objectType, object existingValue,
            JsonSerializer serializer)
        {
            var jsonObject = JObject.Load(reader);
            var contentType = default(IModule);
            var sysProps = JsonConvert.DeserializeObject<ContentfulSystemProperties>(JsonConvert.SerializeObject(jsonObject["sys"]));

            if (sysProps != null && sysProps.ContentType != null)
            {
                switch (sysProps.ContentType.Sys.Id)
                {
                    case "componentPopUpLead":
                        contentType = new PopUpLeadModel();
                        break;
                    case "componentHtmlCallout":
                        contentType = new HTMLCalloutModel();
                        break;
                }

                serializer.Populate(jsonObject.CreateReader(), contentType);
            }
            
            return contentType;
        }
    }

This is the complete code for ContentfulJsonConverter

**Comment by Roblinde** [comment]
Ok, so if you have that one implemented you will only ever be able to deserialize the componentHtmlCallout and componenentPopUpLead.

But in fact I think you can just remove that one and only use a ContentTypeResolver as in this example: https://www.contentful.com/developers/docs/net/tutorials/using-net-cda-sdk/#get-entries-of-multiple-types-or-by-interface
