### ISSUE TITLE
Dependent assembly loading issues

### ISSUE THREAD

**Issue by deanebarker** [contentful/contentful.net#2]
Using VS2017, I created a new class library project (all projects discussed in this issue target 4.6.1) and installed the Nuget package like this:

`Install-Package contentful.csharp -Version 0.5.1-alpha -Pre`

I recreated the `ContentfulGateway` class (see #1).

I created a unit test project with a single test which called the `ContentfulGateway.GetTermBySlug` method (again, from #1). The test failed with an IOException because it couldn't load `System.Diagnostics.DiagnosticSource, Version=4.0.0.0`.

Thinking this may be some issue with the unit testing project specifically, I created a console application project. I attempted to call the same method from above, directly in `Main`.  Execution failed with IOException because it couldn't load `System.Net.Http, Version=4.1.1.0`.

Are these issues with my environment, or issues with dependency definition in the Nuget package?

**Comment by deanebarker** [comment]
I ran into this again, FYI.

```
An exception of type 'System.IO.FileNotFoundException' occurred in Data.dll but was not handled in user code. 

Additional information: Could not load file or assembly 'System.Net.Http, Version=4.1.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.
```

I don't have the same installer available to me this time (on VS2015, not 17), but I installed the `System.Net.Http v4.3.0` Nuget package and that seemed to fix it.

**Comment by Roblinde** [comment]
This is sort of a nuisance, but more in Microsofts hand I'd say. I'm hoping this goes away once we get stable tooling, unfortunately not until spring 2017 it seems.
