### ISSUE TITLE
Installation issue

### ISSUE THREAD

**Issue by peterpociask** [contentful/contentful.net#20]
When I try and install the package into my solution I am getting the following error:

You are trying to install this package into a project that targets 
'.NETFramework,Version=v4.5.2', but the package does not contain any assembly references or content files that are compatible with that framework.

I'm not able to change the .net version in my project.

**Comment by Roblinde** [comment]
Hi Peter, the .Net SDK supports NetStandard 1.4 which means that it supports down to .Net Framework 4.6.1 but unfortunately not below that.

You can read more about NetStandard here: https://blogs.msdn.microsoft.com/dotnet/2016/09/26/introducing-net-standard/

Are you bound to version 4.5.2 of the framework?

**Comment by peterpociask** [comment]
Good catch. I will look into what is involved in changing the .net version. Thanks!

**Comment by Roblinde** [comment]
No problem, also be aware that it supports Asp.Net Core if you wanna go down that route.
