### ISSUE TITLE
Long Text Renderer TagHelper 

### ISSUE THREAD

**Issue by lehoangphan** [contentful/contentful.net#200]
if we use the Rich Text, the SDK support <contentful-rich-text> tag helper 

but if we use Long Text field, is there any  tag helper  for rendering? 

Thanks.

**Comment by Roblinde** [comment]
Hi @lehoangphan 

There is no taghelper for the regular long text field as it's just a regular string. If you're using markdown you could use a third party library like https://github.com/lunet-io/markdig and do `Markdown.ToHtml` on the string returned by the Contentful API.

Hope this helps.
