### ISSUE TITLE
De-serialization issue when using QueryBuilder.FieldEquals with field selector

### ISSUE THREAD

**Issue by pmpontes** [contentful/contentful.net#202]
We were using QueryBuilder.FieldEquals with a field selector for a custom field as follows (for simplicity, Sys.Id is used as example):

`.FieldEquals(obj => obj.Sys.Id, objectId)`

Some objects require a ContentTypeResolver to allow the de-serialization of abstract classes to sub-classes. This works well, but seems to not be used when de-serializing the objects for the purpose of applying the filter using the field selector, as would be expected.
We can work around the issue replacing it with the harcoded field path, which is not ideal:

`.FieldEquals("sys.id", objectId)`

Again, this is not a major issue for issue, rather a suggestion for improvement.

**Comment by Roblinde** [comment]
@pmpontes thanks for the report.

Could you explain what it is that isn't working in this case?
