### ISSUE TITLE
Basic Create Entry Problem

### ISSUE THREAD

**Issue by grimmersnee** [contentful/contentful.net#204]
Please excuse this possibly basic question, but I am not having any luck by following the documentation.

I have the following simple `Faq` content type and I want to use the SDK to create faq items..

![image](https://user-images.githubusercontent.com/31529742/85686046-bbc1cc80-b723-11ea-918b-17e6773c6318.png)

```
   public class Faq : ModelBase
    {
        public int Id { get; set; }
        public string Question { get; set; }
        public Document Answer { get; set; }
    }

    public class ModelBase
    {
        public SystemProperties Sys { get; set; }
    }
```

` await ContentfulManagementClient.CreateEntry(faq, contentTypeId: Constant.ContentType.Faq);`

But I get the follow error.  I can manually create and item and retrieve it using the same model, so I am thinking I must need to populate more properties or something..

![image](https://user-images.githubusercontent.com/31529742/85687824-52db5400-b725-11ea-85d9-ac1b2e82b225.png)

**Comment by Roblinde** [comment]
@grimmersnee when creating entries with this method every property of the class will be serialized to a field in the entry. In this case the Systemproperties of your base class is serialized together with the rest of the props.

**Comment by grimmersnee** [comment]
ok, that makes sense. So, I have removed that base class for now, as i just want to add a record..

Now I get :

![image](https://user-images.githubusercontent.com/31529742/85695035-c54f3280-b72b-11ea-99b1-34f3cc9d89f2.png)

**Comment by Roblinde** [comment]
ah, another unfortunate circumstance is that the models for the Management API differs slightly from the Delivery API. In the management API all properties are wrapped in their locale keys. So you would have to wrap all your properties in dictionaries, something like:


```
Title = new Dictionary<string, string>()
    {
        { "en-US", "Accessories" },
        { "sv-SE", "Tillbehör"}
    },
```

**Comment by grimmersnee** [comment]
yep (a pitty that is..) , just tried this dumbed down example and it worked:

````
var entry = new Entry<dynamic>();
            entry.SystemProperties = new SystemProperties();
            entry.SystemProperties.Id = "testing";

            entry.Fields = new
            {
                question = new Dictionary<string, string>()
                {
                    { "en-US", "123" }
                }
            };

            var result = await ContentfulManagementClient.CreateEntry(entry, contentTypeId: "testing");
````

I am going to ditch the richtext attempt..  Have you had success adding richtext?

**Comment by Roblinde** [comment]
I've had some reports with problems when creating entries with rich text, I will have to investigate further. It should work of course, but there seems to be something with the deserialized format that the API doesn't like sometimes. I'll look into it.

**Comment by Roblinde** [comment]
This should have been solved with recent updates to the rich text serialization. @grimmersnee if you're still having problems, let me know.
