### ISSUE TITLE
Serialization issue with UiExtension

### ISSUE THREAD

**Issue by olee** [contentful/contentful.net#207]
Serializing nearly any Contentful response works correctly and [includes the sys object](https://github.com/contentful/contentful.net/blob/master/Contentful.Core/Models/Management/EditorInterface.cs#L16).
However, for UiExtension this was somehow [implemented differently](https://github.com/contentful/contentful.net/blob/master/Contentful.Core/Models/Management/UiExtension.cs#L17).

I think this should be changed to properly handle this field as well.

**Comment by Roblinde** [comment]
@olee I have just released version 5.0.1 it should hopefully fix this issue. Let me know if it works.
