### ISSUE TITLE
Is "RichText" missing from SystemFieldTypes?

### ISSUE THREAD

**Issue by andersekdahl** [contentful/contentful.net#211]
I might be misunderstanding, but it seams like the `RichText` property is missing on `SystemFieldTypes`? A rich text field shows up as having the type `RichText` in the JSON preview in the CF app, which makes me assume that it should exist in `SystemFieldTypes`?

**Comment by Roblinde** [comment]
Good catch, I will add it to the next release.

**Comment by Roblinde** [comment]
Solved in version 5.0.3
