### ISSUE TITLE
Interfaces on objects inside rich text

### ISSUE THREAD

**Issue by andersekdahl** [contentful/contentful.net#213]
We have an entry type that contains:
```
public List<ICFBlock> Blocks { get; set; }
```

`ICFBlock` is an interface that we use to declare which content types can be placed inside others, and which should be "parent" entries.

When this entry type is placed inside a Rich Text property, we get an error saying:
```
JsonSerializationException: Could not create an instance of type ICFBlock. Type is an interface or abstract class and cannot be instantiated. Path 'blocks[0].sys'.
```
Which is caused by this line:
https://github.com/contentful/contentful.net/blob/master/Contentful.Core/Configuration/ContentJsonConverter.cs#L51

Not sure if that converter is missing the same content type resolving that is used elsewhere?

**Comment by Roblinde** [comment]
Interesting, I'll have a look.

**Comment by andersekdahl** [comment]
Could this have anything to do with #212? If we remove the entry from inside the rich text and instead place it in a property that's a list of entries everything seems to work.

**Comment by Roblinde** [comment]
It could be, I've just released version 5.0.3. If you test with that one, does it work as expected?

**Comment by andersekdahl** [comment]
I'll test it and report back!

**Comment by andersekdahl** [comment]
5.0.3 fixed this issue as well, thanks for the fast response!
