### ISSUE TITLE
Cannot change base URL in ContentfulClient

### ISSUE THREAD

**Issue by roelvandersteen** [contentful/contentful.net#217]
There are situations in which you would like to change the official Contentful URL, for example if your requests to Contentful run through a proxy. Currently you cannot change the private field `_baseUrl`. This means that you have to write your own implementation of the full `IContentfulClient` interface, just to override one value in the provided default implementation.

This can be solved by wrapping the field `_baseUrl` in a property `BaseUrl`, making this property `protected override`, and replacing all places where `_baseUrl` was used with `BaseUrl`. (Except in the constructor.)

**Comment by Roblinde** [comment]
Hi @roelvandersteen thank you for the contribution.

The SDK exposes the `HttpClient` for this purpose. The idiomatic way to add a proxy is to add it through the proxy settings of either the `HttpClient` or the `HttpHandler`. You can read more about it here: https://docs.microsoft.com/en-us/dotnet/api/system.net.http.httpclient.defaultproxy?view=netcore-3.1

I think this would handle the scenario you outlined.

**Comment by roelvandersteen** [comment]
No, our company has the requirement that all external API requests go through Azure API Management. The Contentful endpoint is defined there and our .NET application has no knowledge of the final destination of the request. That is the reason I would like to override the hardcoded Contentful URL.

**Comment by Roblinde** [comment]
I see, however I don't think it's a great idea to expose these internal properties as there is some logic tied to them, such as handling preview api requests. 

If a proxy configuration is not working well, another suggestion would be to create a custom `HttpClientHandler`, inject it into the `HttpClient` and rewriting the url in the `HttpRequestMessage`. 

Something like this:

```
public class AzureMessageHandler : HttpClientHandler
{
     protected override async Task<HttpResponseMessage> SendAsync(HttpRequestMessage request, CancellationToken cancellationToken) {
        
            request.RequestUri = new Uri("https://yourapi.azure.com/");

            return await base.SendAsync(request, cancellationToken);

    }
}
```

Then inject this handler into the httpclient when wiring up your `IContentfulClient`.

```
var httpClient = new HttpClient(new AzureMessageHandler());
var contentfulClient = new ContentfulClient(httpClient, new ContentfulOptions()
            {
                DeliveryApiKey = "123",
                SpaceId = "666",
                UsePreviewApi = false
            });
```

The above should of course be moved to the startup configuration of your app to make sure only 1 httpclient is used throughout the app etc.

**Comment by roelvandersteen** [comment]
Okay, that approach would work. I still don't like the Contentful base URL to be encoded into a private variable, but since you don't seem inclined to change it, I will go with your proposed solution.

Robert, thanks for your help and comments.

**Comment by Roblinde** [comment]
Happy to help. Thanks for the discussion.
