### ISSUE TITLE
Is there a way to add a parent element to any HTML tag?

### ISSUE THREAD

**Issue by fuyunekojima** [contentful/contentful.net#219]
RichText in Contentful is deserialized to Document type, and Document is converted to MarkupString type for use. (I created an extension method).
When using the "code" tag in Contentful's RichTextEditor, the "pre" tag does not exist in the parent element, so line breaks and indentation are ignored by the browser.

Is there a way to add a parent element to any HTML tag?

```C#
        public static MarkupString ToHtml(this Document doc)
        {
            var renderer = new HtmlRenderer();
            var html = renderer.ToHtml(doc).GetAwaiter().GetResult();
            return (MarkupString)html;
        }
```

using Blazor ServerSide.

```razor
    <div>
        @entry.Content.ToHtml()
    </div>
```

Model

```C#
    public class ContentfulEntry
    {
        public SystemProperties Sys { get; set; }
        public string Title { get; set; }
        public Document Content { get; set; }
        public string Description { get; set; }
        public Asset Cover { get; set; }
    }
```

**Comment by fuyunekojima** [comment]
After reading the code for a while, either create a new "CodeRenderer" -like renderer that implements the "IContentRenderer" interface, or copy the HtmlRenderer and rewrite the HTML text with a regular expression as the final step in the "ToHtml" method. It seems that you need to take the method.

**Comment by fuyunekojima** [comment]
We have tentatively taken this action.
I copied "HtmlRenderer" and rewrote the process.
```C#
        public async Task<string> ToHtml(Document doc)
        {
            var sb = new StringBuilder();
            foreach (var content in doc.Content)
            {
                var renderer = _contentRendererCollection.GetRendererForContent(content);
                sb.Append(await renderer.RenderAsync(content));
            }
            
            return ReplaceCodeToPreCode(sb.ToString());
        }

        public string ReplaceCodeToPreCode(string htmlText)
        {
            var pat = new Regex(@"<code>.*?</code>", RegexOptions.Singleline);
            return pat.Replace(htmlText, match =>
            {
                return $"<pre>{match.Value}</pre>";
            });
        }
```

**Comment by Roblinde** [comment]
@fuyunekojima what you could do is to implement your own `IContentRenderer`, possibly even copying the `TextRenderer` and modifying the parts you want, then pushing it back into the `HtmlRenderer` with the `AddRenderer` method. Just make sure that your custom renderer has a lower `Order` property than the default one and it would be used instead of the normal `TextRenderer`

**Comment by fuyunekojima** [comment]
I was able to create a useful Custom renderer based on your code.
Thank you very much.

multipost: [stackoverflow](https://stackoverflow.com/questions/65264081/about-the-code-tag-in-the-richtext-field-of-contentful-dotnet-sdk)
