### ISSUE TITLE
Create Content Type - DisplayField not set

### ISSUE THREAD

**Issue by matt-hammond** [contentful/contentful.net#22]
Given I a creating a content type using the .Net API with two fields, "id" and "title"
And I set the DisplayField to "title"
When I call CreateOrUpdateContentTypeAsync
Then the content type is created 
**_And the DisplayField is null_** (should be "title")

Given I set the DisplayField via Contentful UI
And then call GetContentTypeAsync
And can see DisplayField is correctly returned set to "title"
When I pass the same content type to CreateOrUpdateContentTypeAsync
**_Then the DisplayField is reset to null_** (should be "title")

**Comment by Roblinde** [comment]
Thanks, I'll look into this!

**Comment by Roblinde** [comment]
Thanks for finding this Matt, a fix will appear on nuget momentarily.

**Comment by matt-hammond** [comment]
Excellent. I can confirm it is fixed in the latest Nuget pacakge. Many thanks for such a speedy response.
