### ISSUE TITLE
Deserialization performance

### ISSUE THREAD

**Issue by andersekdahl** [contentful/contentful.net#223]
I'm looking into performance right now in our app, and when digging into traces I see that a large amount of time is spent deserializing the JSON from the Contentful API. I'm looking at a trace where the entire request takes 37ms. The request to the Contentful API takes just 2-3ms (super impressed by that btw!), but the total time spent in dealing with JSON in the SDK is 30.91ms, as seen here:

![image](https://user-images.githubusercontent.com/163637/108683159-83ac9c80-74f1-11eb-87cf-0e997d467487.png)

We recently saw the same thing for another API we're using where we parse the JSON ourselves. We used `JObject.Parse()` and mapped dynamically using a lot of `JToken`s and `JObject`s. Then we changed that to `JsonConvert.DeserializeObject<Xyz>()` where `Xyz` is a class we created that fully represented the API response, and then mapped from that type to the structure we wanted.

We saw JSON handling drop from ~30ms to something like 3-4ms. And I think we could probably expect the same difference here. It's probably a relatively big thing to change, but I think it's worth it since you can remove the current tricks involved like injecting `$type` to make JSON.NET understand. It would also open up for more userland control for unexpected situations, such as trying to map an entry of a content type that doesn't exist in code, which right now is quite limited because it's under JSON.NETs control.

Is this a change you'd be interested in making?

**Comment by andersekdahl** [comment]
Here's another trace that's a lot worse:
![image](https://user-images.githubusercontent.com/163637/109411756-8fdaa300-79a4-11eb-8dd2-75c0e860b34c.png)

The JContainer.AddInternal drills down into a really expensive `Framework/Library Dictionary`2.TryInsertFramework/Library Dictionary`2.TryInsert Expanded | System.Private.CoreLib`. This is for quite a small piece of JSON, essentially the same JSON as in my first trace.

Would really appreciate your view on this. We're getting closer to launch and this is going to be a bit of a blocker for us.

**Comment by Roblinde** [comment]
Hi @andersekdahl 

The thing that takes time in the SDK is the link resolution. A lot of restructuring of the json goes on there to makes sure you can serialize into an entire object graph. I have contemplated adding a more "raw" method to the `IContentfulClient` that just returns the json as is, and leaves link resolution up to the client. Nothing on the road map right now though.

If you have some performance critical calls I'd suggest using the `HttpClient` directly and deserializing the response in the most performant manner suitable to your needs.

**Comment by andersekdahl** [comment]
We ended up doing just that, implementing our own client class basically. There were a few methods we had to copy from the SDK classes, would be nice if that wasn't needed.

The approach is basically:
- Use `JsonTextReader` to deseralize a JSON stream char by char to an intermediate object that is basically a 1-to-1 representation of what the API responds with. `JsonTextReader` rather than `JsonConvert.DeserializeObject<T>()` because the field values are so dynamic.
- Find references to linked entries and assets as we go, collect all ids and send a new request for those. And repeat until no more links are found or our max depth is reached. This turned out to be more efficient than using `?includes=` in the API request since that might give us a very big payload depending on what the linked entry is. In a lot of cases we're only interested in one or two properties but some entries are very big. So we load them using `?select=`. We also statically cache all entry and asset ids that an entry linked to, so that we can preload all of them at once the next time the same entry is requested.
- Map from the intermediate object to the model classes using reflection, and mapping nested objects as we find them.

**Comment by awa-nc** [comment]
Hi @andersekdahl,

We are experiencing the same problem (performance bottleneck), and was wondering what were your long term experiences with the custom approach? We are contemplating whether we should take the same route, or a better approach has emerged.

Thank you.

Best regards,
Andreas

**Comment by andersekdahl** [comment]
It worked out very well for us but it did mean that we had to stop using the official SDK in a lot of places. The code to deserialize got quite complex as we did it with a custom `JsonConverter` that read token by token, but I think it was worth it given the perf we got.

**Comment by awa-nc** [comment]
Hi @andersekdahl / all who may be interested,

I wanted to provide an update since we have now written a custom CDA integration which fetches the referenced entries per included level. While the parsing performance/CPU utilization seems to be better, we have run into a new problem: rate-limits. 

In hindsight it should not have been a surprise to us since we have been struggling with rate-limits for a long time*, but considering that our average query include level is about 4 and the new algorithm makes a CDA request per level, we are now generating as much as 4 x the amount of requests. (The rate-limiter does not consider the size of the query/payload but only that it was a request.)

In an attempt to work around the rate-limit we are considering keeping the custom integration but changing it to included queries i.e. with referenced entries like the SDK. The link resolution is IMO the bottleneck of the SDK and we can replace it with something more performant.

* We have dozens of full time editors (at times more) producing content as well as automated systems importing content. Since a publish event purges the global cache, the CDN cache is often empty, at which point the rate-limit applies.

**Comment by andersekdahl** [comment]
We ended up in almost the same place as you but for different reasons. We changed our solution to not use the CDA for content delivery. Instead we had to listen to changes from Contentful, fetched the data we need and prebake it into models that we stored in Redis which we then used to fetch the data from to serve API clients.

**Comment by awa-nc** [comment]
That sounds like a very scalable approach - feels a bit like SSG/model generation. 

If you are not using the CDA, are you then getting the data you need from the webhook request payload (publication event), or are you using the Sync API for change feeds?

**Comment by andersekdahl** [comment]
IIRC we used the management API in the webhook handler to fetch the entities needed to rebuild the data in Redis.

We didn't have a lot of editors invalidating the CDA but we still got a lot of unexpected cache misses so we had to go the Redis route.
