### ISSUE TITLE
AssetStructure data is null in some Document instances

### ISSUE THREAD

**Issue by drachele** [contentful/contentful.net#227]
Hi,

I've come across a strange issue with the `Document` class, where some instances of `AssetStructure` have a null data target, even though the data is being returned correctly from the Contentful REST API.

This is causing the `AssetRenderer` to throw an exception when calling the `.ToHtml()` method on the `HtmlRenderer`.

You can see here an example of it being set in one instance, but not in another, even though they are both set correctly in the Contentful admin:

![image](https://user-images.githubusercontent.com/825135/110918566-36af2f80-8313-11eb-88a2-d4e97344d552.png)

I have saved the response from Contentful for reference, but would prefer not to post it here. I can send it to you privately if it helps.

This also seems to happen randomly in other scenarios as well. Sometimes, an `Asset` is null, even though it is correctly set in the Contentful admin, and it is being returned correctly by the Contentful API.

Any help would be greatly appreciated. The randomness of this is causing a lot of issues on our website.

Thanks,
Dan.

**Comment by drachele** [comment]
Hi,

I've been doing some debugging, and I think I know what the issue is.

In this API request, the same assets are being referenced by different entities, so once the asset is resolved for one entity, it is not resolved again for other references.

The culprit seems to be the `ResolveLinks()` method in `ContentfulClient.cs`.

I will see if I can fix it and submit a PR, but if you'd like to fix this yourself (since you're more familiar with the code), then feel free! :)

Thanks,
Dan.

**Comment by Roblinde** [comment]
Hi @drachele 

I think you've run into what I describe here: https://robertlinde.se/posts/why-is-my-item-null-contentful-net/ 
Have a read through and let me know if it helped you.

**Comment by drachele** [comment]
Hi @Roblinde

I have tried setting `ResolveEntriesSelectively` to both true and false - both give the same results unfortunately.

**Comment by drachele** [comment]
I think I have an edge case here which is causing the issue.

I have an `Asset` which is referenced by a gallery entry, but is also referenced within the rich text field of an article entry. This image asset gets resolved to the gallery, but when it tries to resolve it for the rich text field, it gets skipped, because of this code:

![image](https://user-images.githubusercontent.com/825135/110948628-7d178500-8339-11eb-87a7-2f86c45c88f4.png)

The asset ID is part of the `processedIds` collection, so it doesn't try and resolve it, which ends up leaving the `Data.Target` field as null, which in turn causes the `AssetRenderer` to throw an exception.

**Comment by Roblinde** [comment]
Hmm, which version of the SDK are you running? I found a bug in the implementation that I recently patched.

**Comment by drachele** [comment]
The latest - 6.0.2.

**Comment by Roblinde** [comment]
😢 ok, maybe I broke something. I would love to look at the json structure so I can replicate it in a unit test. Could you send it to me privately? Perhaps in our community slack? Just @Robban and I'll have a look as soon as possible.

**Comment by drachele** [comment]
I have emailed the JSON to your Contentful email address.

Please let me know if this won't work, and I will send via Slack.

Thanks.

**Comment by Roblinde** [comment]
Issue resolved in #229
