### ISSUE TITLE
QueryBuilder.ContentTypeIs() uses Add() which can cause multiple content_type parameters

### ISSUE THREAD

**Issue by andersekdahl** [contentful/contentful.net#233]
When using:
```
client.GetEntriesByType(contentType, queryBuilder);
```
a call is made to:
```
builder.ContentTypeIs(contentTypeId);
```

which makes this call:
```
_querystringValues.Add(new KeyValuePair<string, string>("content_type", contentTypeId));
```

This causes trouble when wrapping SDK calls in retries, because a retry causes the `content_type` parameter to be added twice and the API call fails.

**Comment by Roblinde** [comment]
This should now be fixed in version 6.0.6
