### ISSUE TITLE
Documentation does not match implementation

### ISSUE THREAD

**Issue by follesoe** [contentful/contentful.net#235]
The documentation for getting started with Rich Text does not match the library implementation: https://www.contentful.com/developers/docs/net/tutorials/rich-text/

I.e. the example:

```csharp
public class CustomViewContentRenderer : BaseContentRenderer
{
    public CustomViewContentRenderer(IRazorViewEngine razorViewEngine, ITempDataProvider tempDataProvider, IServiceProvider serviceProvider) : base(razorViewEngine, tempDataProvider, serviceProvider)
    {
    }

    public override bool SupportsContent(IContent content)
    {
        return content is SomeModel;
    }

    public override string Render(IContent content)
    {
        var model = content as SomeModel;

        return RenderToString("SomeView", model);
    }
}
```

Does not make sense, as the file https://github.com/contentful/contentful.net/blob/master/Contentful.AspNetCore/Authoring/BaseContentRenderer.cs only contains a `RazorContentRenderer` abstract class and no `BaseContentRenderer` class.

**Comment by Roblinde** [comment]
@follesoe than you! I'll get that changed. 

Was that the only error you found or were there others?

**Comment by follesoe** [comment]
@Roblinde The documentation did not remind me to add `@addTagHelper *, Contentful.AspNetCore` to the `_ViewImports.cshtml` file, so took some time before I could understand why the custom tag helpers did not render.

**Comment by Roblinde** [comment]
@follesoe Thanks, I'll make sure to add that too.

**Comment by Roblinde** [comment]
Documentation is updated.
