### ISSUE TITLE
Webhook middleware provide IServiceProvider to consumer

### ISSUE THREAD

**Issue by carlin-q-scott** [contentful/contentful.net#236]
As a consumer of a webhook call, I expect to be able to access the services I have registered in my DI container, such as my database interface. The consumer function only receives the deserialized request body, and no request context. The authenticator function on the other hand does receive the HttpContext where I can access the IServiceProvider to retrieve my DbContext.

The documentation for the webhook middleware is located here: https://www.contentful.com/developers/docs/net/tutorials/aspnet-core/#working-with-webhooks-and-middleware

**Comment by Roblinde** [comment]
Wouldn't something like this work in that scenario?

Inside the `Configure` method of `Startup.cs`

```
var db = app.ApplicationServices.GetService<IDbServices>();
            app.UseContentfulWebhooks(c =>
            {
                c.AddConsumer<Entry<dynamic>>("*", "*", "*", (s) =>
                {
                    db.DoSomething(s.Fields.Name);
                    return new { Test = s?.SystemProperties.Id };
                });
            });
```

**Comment by carlin-q-scott** [comment]
I wasn't aware of the ApplicationServices service provider. As shown in your example, that would create a singleton of a dbcontext, which wouldn't work with Entity Framework since it expects each thread to have its own instance of the context. I could do the following, but it seems like it would be pretty simple to add an overload to AddConsumer that provides the request context service provider that is already scoped appropriately.
```c#
app.UseContentfulWebhooks(c =>
            {
                c.AddConsumer<Entry<dynamic>>("*", "*", "*", (s) =>
                {
                    using (var scope = app.ApplicationServices.CreateScope());
                    var provider = scope.ServiceProvider;
                    var db = provider.GetService<DbContext>();
                    db.DoSomething(s.Fields.Name);
                    return new { Test = s?.SystemProperties.Id };
                });
            });
```

**Comment by Roblinde** [comment]
Indeed, I'll look into it.

**Comment by Roblinde** [comment]
There's now an overloaded consumer in version 6.0.7 that accepts an HttpContext. Hope it helps you out.
