### ISSUE TITLE
Not-Easily Replicated: Client Is aggregating query parameters

### ISSUE THREAD

**Issue by nteague22** [contentful/contentful.net#239]
I have been using the .Net tooling at my workplace, in an ASP.Net 4.x application and cannot share any code snippets per rules -- but can say that we began using the .Net SDK, and our code DI injects the client as a singleton. Where httpclient can safely live as a singleton, this seemed fine -- but recently if we get enough traffic that pushes to or near the 429 error, we have begun getting requests that came back as having include multiple times on the query.  I can say it typically starts when we have elevated traffic, and even when testing locally with load -- I cannot recreate it.  I looked through the code and am not sure if it is either A. Because the retry uses a cloning process to re-request, and|or if having the client loaded once for all requests is breaking its thread safety somehow.  I am sorry for a lack of code examples, but I can say it throws the ContentfulCoreException, complaining on include multiple times, and to use a orders=foo,bar syntax (even though our code only ever pushes the include once on the querybuilder

**Comment by Roblinde** [comment]
@nteague22 thanks for the report. I'll see if I can replicate it with some unit tests. I do have a hard time imagining why this would happen though.

**Comment by Roblinde** [comment]
Quick question, which method are you calling. Is it the generic `GetEntries<T>` or is it `GetEntriesByType<T>`?

**Comment by Roblinde** [comment]
I've been trying to replicate this, but I can't seem to get this behaviour. Are you using the retry-functionality of the SDK or have you written your own? I feel like if this duplication would occur it should double the entire request URI and not just part of the query-string. We had a bug a while back with the query-builder however  #233 maybe this is something similar if you're writing your own logic and reusing the same querybuilder?

**Comment by nteague22** [comment]
I had experienced the error when using one querybuilder instance per call, and the retry from the sdk.  I had not applied any custom logic to the process. I have it calling the generic Get content. For a time I had looked at trying to re-request the call manually, but saw the retry functionality was included in the sdk. Currently I have moved to not using the retry from the sdk, and rather handling the targeted exception with the hint cool down time, which is why I had asked -- is the ContentfulClient not safe at Singleton scope?

Get Outlook for Android<https://aka.ms/AAb9ysg>

________________________________

**Comment by Roblinde** [comment]
I think it should be fine to use as a singleton, can't see what the problem could be here. If you try using it as a transient instead, does the same problem occur?

**Comment by nteague22** [comment]
I had not tried that as of yet, where this client is running the vast majority of the time on a high traffic web application as a singleton, I was not able to shift it to Transient, with the memory consumption increase.  I had this occur very infrequently that I did not think the client is faulty -- I just wanted to make sure there was not a known error I was causing.  The only thing I could trace is if the cloning of the headers and other content was somehow cloning the target path to the new HttpRequestMessage, but then also having the querybuilder.Build() call compose the filters -- and then concatenate onto the outgoing path,
But it almost seems like it has to hit in a very precise timing -- it only happens in limited edge case situations

**Comment by nteague22** [comment]
Possibly the related issue applies, I can make a pr if able or if you guys keep it in house -- to possibly check for the "include" parameter  to be distinct anyhow -- since the api's response reflects multiples as invalid.  Possibly just a 
```
if (!_queryParameters.Any(q => q.Key.Equals("include", StringComparison.OrdinalIgnoreCase)) { // assignment };
return this;
```

**Comment by nteague22** [comment]
So through investigation I identified that the process as I implemented it was using a strategy pattern, while composing the querybuilder minus the include in the service, and in the client property was consuming the querybuilder as a parameter and calling with .Include -- so the retry logic was referencing the instance of querybuilder from the service, was being mutated in the client wrapper.  So I have corrected our code implementation, but still think it would be helpful for the client to convey that only one instance of Include is permitted.  So I am closing this for now as not breaking

**Comment by Roblinde** [comment]
Excellent, thank you for the investigation and happy it got resolved for you.
