### ISSUE TITLE
Custom JSON Serializer

### ISSUE THREAD

**Issue by weslenng** [contentful/contentful.net#240]
How can I use a custom JSON serializer to Contentful.NET?
It's very useful for F# integration. Newtonsoft doesn't handle `option` and other F# types very well

**Comment by Roblinde** [comment]
Hi @weslenng the SDK is currently entirely dependent on the Newtonsoft library for deserialization. If you need to completely customise this you would have to make the HTTP calls directly to Contentful yourself. This is what I've done with F# in the past.
