### ISSUE TITLE
AssetRenderer.Render throws NullReferenceException when linked asset has no file

### ISSUE THREAD

**Issue by rjgotten** [contentful/contentful.net#249]
The `AssetRenderer.Render` method throws a `NullReferenceException` on line 646 when attempting to render the opening tag of an `asset-hyperlink` node when the actual asset has no file data.

https://github.com/contentful/contentful.net/blob/af6781f28364b69a948f03d666d850d679e5b4b9/Contentful.Core/Models/Authoring.cs#L635-L664

Though probably a bad idea - it's possible to publish an asset that has no file, in particular for multi-lingual assets; and then to complete forget about it by the time you actually link to the asset in a piece of rich text content.

For such cases I'd probably expect as a failsafe an inert hyperlink without a href attribute to be rendered. Technically correct; because there's nothing to actually link to. To accomplish this line 646  could be adapted to something like:

```cs
var assetUrl = asset.File?.Url;
sb.Append(string.IsNullOrEmpty(assetUrl) ? $"<a href=\"{assetUrl}\">" : "<a>"); 
```

**Comment by Roblinde** [comment]
This should now be fixed in version 6.0.13
