### ISSUE TITLE
Excessive RAM usage with getting entries by type

### ISSUE THREAD

**Issue by pklimczu** [contentful/contentful.net#251]
Hello,

I have encountered an issue with - as I believe - excessive RAM usage when JSON received from Contentful API is being parsed with this library. 
There is a Contentful model with 13 fields (including 4 similarly sized references and 3 medias). In one query there is an attempt to obtain 20 entries of that model (with all references being resolved), the resulting JSON is 8-9k-lines sized. The total number of that model entries is approximately 250 so there is a loop that runs 13 times. It all works correctly but I have noticed that each request causes noticeable RAM usage. Here is a screenshot from dotMemory with a snapshot:

![image](https://user-images.githubusercontent.com/5957413/132042533-5adf8b50-126d-496b-847d-d820a8aedd56.png)

Each requests consumes several hundreds megabytes of RAM. It is then reclaimed by GC but given that this code is supposed to work on the server, just 5 users using the service simultaneously results in 1 GB RAM being used (which is rather a compelling number).

It is understandable that some resources are required to deserialize received response but these numbers are a little too big for me. I would suspect that something may be wrong here.

This is a chunk of my code that results in mentioned issue:
```
var retrieved = ContentfulQueryLimit; // set to 20 
const string contentTypeId = InfrastructureConstants.ContentfulContentTypeIdBusiness; // Contentful id of the resource

var queryBuilder = new QueryBuilder<BusinessDto>()
    .Limit(ContentfulQueryLimit);

var entries = await _contentfulClient.GetEntriesByType(contentTypeId, queryBuilder, cancellationToken);
IEnumerable<BusinessDto> businessCandidates = entries;

while (entries.Total > retrieved)
{
    queryBuilder = new QueryBuilder<BusinessDto>()
        .Skip(retrieved)
        .Limit(ContentfulQueryLimit);
        
    var extraEntries = await _contentfulClient.GetEntriesByType(contentTypeId, queryBuilder, cancellationToken);
    businessCandidates = businessCandidates.Concat(extraEntries);
    retrieved += ContentfulQueryLimit;
}
```

**Comment by Roblinde** [comment]
@pklimczu thank you for this report. The problem in these kinds of scenarios is almost always in reference resolution. Apart from that the SDK is just a "pure" deserialization of the JSON, but some more magic is required to resolve every reference correctly. So one trick for reducing memory consumption and overall cpu usage is to only include the references you need for your query. This in conjunction with the `Include` parameter that specifies how many levels of referenced content you want to include can be helpful.

However, in the example above I have a few questions. Why is the `ContentulQueryLimit` set to 20? This means you will only fetch 20 entries a time and result in a total of 13 calls to the API endpoints. Is the api-response larger than the 7mb the API allows if you go with the standard 100?

The issue with iterating over the collection 13 times is not only that you need to keep the entire deserialized structure in memory for the full operation, but also that if there are entries in different queries that references the same content it needs to be deserialized twice (or even more than that depending on in how many of the calls include the same reference).

**Comment by pklimczu** [comment]
Thank you @Roblinde for your answer.
Unfortunately, there is no use of `Include` parameter here as the whole structure is only two-levels depth.

If there would be no `ContentulQueryLimit`, the RAM consumption would be even bigger for some reason. Your explanation is very convincing, however something else must be wrong since setting that variable to 300 is skyrocketing the RAM usage by 100%.

I wonder if there might be some issue with `errors` returned by Contentful. I mean this top-level key in returned JSON (the others are `sys`, `total`, `skip`, `limit` and `includes`). Another suspicious thing is that the application is running on official Microsoft docker container with .NET 5.0. The issue described here seems to be less visible when I ran the application on Windows.

**Comment by Roblinde** [comment]
Hmm that's interesting. I wonder if the deserialized structure is very large in memory for some reason... are there any infinite loops in the structure that could explain something like this perhaps?

**Comment by pklimczu** [comment]
No, no loops.
I made another attempt to understand what is going on here by cloning this library and creating such a small program inside:
```
            var httpClient = new HttpClient();
            var deliveryApiKey = "deliveryApiKey";
            var previewApiKey = "previewApiKey";
            var spaceId = "spaceId";

            var client = new ContentfulClient(httpClient, deliveryApiKey, previewApiKey, spaceId);
            var queryBuilder = new QueryBuilder<BusinessDto>().Limit(300);
            var response = await client.GetEntriesByType("business", queryBuilder, CancellationToken.None);
```
The following breakpoints were added:
* one before `GetEntriesByType` execution,
* another on line 192 of `ContentfulClient.cs` (line: `ReplaceMetaData(json);`)
* another on line 227 of `ContentfulClient.cs` (line: `var collection = json.ToObject<ContentfulCollection<T>>(Serializer);`)
* the last one after having the response ready

And here are the memory snapshots made while the program was stopped on each breakpoint:
![image](https://user-images.githubusercontent.com/5957413/132763387-622cd7b3-2336-475c-b415-461089cb343f.png)

So 50 MB is taken solely by parsing the raw string to the `JObject` and another 35 MB for reference resolving but only ~2MB for expected object creation.

**Comment by Roblinde** [comment]
It would be interesting to know how much memory would be consumed if you used Json.NET directly. The SDK relies heavily on the functionality from there to handle the deserialization.

**Comment by pklimczu** [comment]
Well, so it seems that Json.NET is the main factor contributing to the overall RAM usage. Moreover, it seems that we are somewhat stuck here since there is no other way to parse that JSON from Contentful.

Thank you @Roblinde for your answers here ;)
