### ISSUE TITLE
Reverse Sort Order throws Exception

### ISSUE THREAD

**Issue by tarun713** [contentful/contentful.net#252]
Hello! Not sure if this is a real issue or I am doing something wrong. Trying to pull the 5 latest entries of a content type (ideally by my PublishedDate attribute, but createdAt throws the same error.

This code works without issue (commented out the Limit() to keep it basic).

     var builder = QueryBuilder<BlogPost>.New.ContentTypeIs("blogPost").OrderBy("sys.createdAt"); //.Limit(5);
     var posts = _contentfulClient.GetEntries(builder).Result;

However, this code, trying to reverse the order, throws an exception. Is this a bug or is there a different way I should be reversing the order of the sort?

     var builder = QueryBuilder<BlogPost>.New.ContentTypeIs("blogPost").OrderBy("-sys.createdAt"); //.Limit(5);
     var posts = _contentfulClient.GetEntries(builder).Result;

System.AggregateException
  HResult=0x80131500
  Message=One or more errors occurred. (Error setting value to 'Target' on 'Contentful.Core.Models.EntryStructureData'.)
  Source=System.Private.CoreLib
  StackTrace:
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at System.Threading.Tasks.Task`1.get_Result()
   at ---TRUNCATED---

  This exception was originally thrown at this call stack:
    [External Code]

Inner Exception 1:
JsonSerializationException: Error setting value to 'Target' on 'Contentful.Core.Models.EntryStructureData'.

Inner Exception 2:
InvalidCastException: Unable to cast object of type 'MyCode.Entities.BlogPost' to type 'Contentful.Core.Models.IContent'.

BlogPost definition:

      public class BlogPost
      {
        public SystemProperties Sys { get; set; }

        public string Title { get; set; }

        public string Slug { get; set; }

        public string Description { get; set; }

        public Document Body { get; set; }

        public DateTime PublishDate { get; set; }

        public List<string> Tags { get; set; }

        public Asset? HeroImage { get; set; }

        public Person Author { get; set; }

        public string Category { get; set; }

        public int Order { get; set; }
    }

**Comment by Roblinde** [comment]
Hello @tarun713 

It seems you might have entries in your rich text (it has nothing to do with the sort order, but rather it seems that only when you sort in reverse order do you get any of the entries that have another entry in their rich text). If you add the `IContent` interface to your `BlogPost` class I think the error should go away.

You can read more about working with custom node types in rich text here: https://www.contentful.com/developers/docs/net/tutorials/rich-text/

Hope this helps you move forward.

**Comment by tarun713** [comment]
Adding IContent did solve the issue and I will take a closer look at the docs you linked. Appreciate it!
