### ISSUE TITLE
How to output rich text without taghelper's tag (contentful-rich-text)?

### ISSUE THREAD

**Issue by nickv-getcodified** [contentful/contentful.net#255]
Consider this code:
```razor
<div>
  <contentful-rich-text document="@Model.ViewModel.BlockRichText"/>
</div>
```
this outputs something like this inside div tag:
```html
<div>
  <contentful-rich-text>
    <p>...</p>
  </contentful-rich-text>
</div>
```

Is this the intended behaviour or I can omit `<contentful-rich-text>` tag from output somehow? I'm using it in partial views and pages in aspnetcore mvc project and this extra tag ruins frontend styles declared like this:
```css
div > p {
  ...
}
```
because `p` element is no longer nested in div element.

For now I'm using this code and it works fine:
```razor
@inject HtmlRenderer htmlRenderer
...
<div>
  @Html.Raw(await htmlRenderer.ToHtml(Model.ViewModel.BlockRichText))
</div>
```
and it produces:
```html
<div>
  <p>...</p>
</div>
```

**Comment by nickv-getcodified** [comment]
Solved this by extending `ContentfulRichTextTagHelper` and setting `TagHelperOutput.TagName` property to `null`

```C#
[HtmlTargetElement("contentful-rich-text-omitted", TagStructure = TagStructure.NormalOrSelfClosing)]
public class ContentfulRichTextOmittedTagHelper : ContentfulRichTextTagHelper
{
    public ContentfulRichTextOmittedTagHelper(HtmlRenderer renderer) : base(renderer)
    {
    }

    public override async Task ProcessAsync(TagHelperContext context, TagHelperOutput output)
    {
        output.TagName = null;
        await base.ProcessAsync(context, output);
    }
}
```
then including this taghelper in `_ViewImports.cshtml`

**Comment by Roblinde** [comment]
hmm maybe that should be the standard behaviour... I'll consider it. Glad you got it working!
