### ISSUE TITLE
Returned C# objects have Revision but not Version

### ISSUE THREAD

**Issue by mattthr** [contentful/contentful.net#260]
Have hit a problem trying to update contentful items using the C# API - using CreateOrUpdateEntry seems to require you to increment the version number, otherwise, it complains you're not updating the most recent version. But when I fetch an existing item, it doesn't seem to have a version?

`                var idQuery = QueryBuilder<Entry<dynamic>>.New.ContentTypeIs(ContentfulEntryType).FieldEquals("fields.myId", "myIdValue");
                var idItems = await this.client.GetEntries(idQuery);`

Looking at the items returned via this query in the debugger, the SystemProperties.Version property is null, even though I can see via the UI that the items I'm looking at have a version number. 

How do I get the version via the .Net client?

**Comment by Roblinde** [comment]
The version is only returned for calls using the CMA (Contentful Management API), which means you need to use the `ContentfulManagementClient` to fetch your entries. You can read more about working with entries and the CMA here: https://www.contentful.com/developers/docs/net/tutorials/management-api/#working-with-entries
