### ISSUE TITLE
Problem GetEntry with Entry<T> deserializing Fields property

### ISSUE THREAD

**Issue by nholik** [contentful/contentful.net#261]
I was trying to take advantage of the note in the documentation regarding using Entry<T> to resolve metadata and sys properties as per
https://contentful.github.io/contentful.net-docs/api/Contentful.Core.ContentfulClient.html#methods
 and
https://github.com/contentful/contentful.net/blob/bba183e94de66a1f745fb79f6746c2a0e6ff4e11/Contentful.Core/ContentfulClient.cs#L111

However, it looks like for the GetEntry (for a single entry) method is not deserializing the fields to the Fields property.  I was proving this to myself where
`GetEntry<MyObject>(...)`
would fill all properties, but trying
`GetEntry<Entry<MyObject>>(...)`
will only fill the system properties and metdadata, but leave the Fields property null in this case.

Looking it over, it seems to me that maybe this documentation only applies to the methods that return multiple entries, but not the single entry method?  Not sure if I am missing something or if this is actually a mismatch between the docs and implementation.

I'd be happy to submit a PR if it is agreed and would be a valid change.  Essentially I think that for
`GetEntries<T>(...)` if `T` is `Entry<U>` then it would deserialize such that Fields is type `U`.
ex.
```csharp
public class ProductFields
{
    public string ProductName { get; set; }
    public string Price { get; set; }
    public string Description { get; set; }
}
```
```csharp
var result = await client.GeEntries<Entry<ProductFields>>("123");
// here result.Fields is an instance of ProductFields with values entryid 123,
// result.SystemProperties and result.Metadata are as expected
```

**Comment by Roblinde** [comment]
@nholik thanks for the PR, releasing a new version shortly that includes this fix.
