### ISSUE TITLE
Default value support in Field object

### ISSUE THREAD

**Issue by jbe-emakina** [contentful/contentful.net#263]
Hello,

I'm trying to add a default value in my field object but I think that feature is not yet supported by the framework.
Do you know when this feature will be available?

**See related documentation**: https://www.contentful.com/developers/docs/references/content-management-api/#/reference/content-types/content-type => paragraph "Default values"

Thanks for your support,
Kind regards,
Jonathan
[Emakina.BE](https://www.emakina.com/en-be)

**Comment by Roblinde** [comment]
Hi @jbe-emakina I'm expecting to release a version supporting this during the week. I'll let you know when it's available.

**Comment by jbe-emakina** [comment]
Thank you @Roblinde for your support ;)

**Comment by Roblinde** [comment]
@jbe-emakina This should now be supported in version 6.0.18.

You do something like this:

```
  var contentType = new ContentType();
  contentType.SystemProperties = new SystemProperties();
  contentType.SystemProperties.Id = typeId;
  contentType.Name = name;
  contentType.Fields = new List<Field>()
  {
      new Field()
      {
          Name = "Field1",
          Id = "field1",
          @Type = "Symbol",
          Required = true,
          Localized = true,
          Disabled = false,
          Omitted = false,
          Validations = new List<IFieldValidator>
          {
              new SizeValidator(2,8)
          },
          DefaultValue = new Dictionary<string, object> 
          { 
              { "en-US", "defaulto" },
              { "de-DE", "German  defaulto" }
          }
      }
  };
```
Let me know how it works for you.
