### ISSUE TITLE
Version mismatch error

### ISSUE THREAD

**Issue by coherent-edkarhuber** [contentful/contentful.net#264]
Hello,

Could you explain how does updating assets work?
I use the following simple code:
```csharp
var asset = await _client.GetAsset("<my-asset-id>");
await _client.CreateOrUpdateAsset(asset);
```
and always get the exception: `Version mismatch error. The version you specified was incorrect. This may be due to someone else editing the content.'`

I've also tried to update a version somehow: `assetOld.SystemProperties.Version -= 1; +=1` but in all cases I got the same result.
Using **contentful.csharp 6.0.17**

**Comment by Roblinde** [comment]
Hello @coherent-edkarhuber what happens if you specify the version from the asset you just fetched:

```
var asset = await _client.GetAsset("<my-asset-id>");
await _client.CreateOrUpdateAsset(asset, version: asset.SystemProperties.Version);
```

The idea here is that the API expects you to specify a version of the aset (or entry) that you're trying to update to make sure noone has been making changes to it since you fetched it.

**Comment by coherent-edkarhuber** [comment]
Thanks @Roblinde . 
I'll try it and let you know.. I wasn't aware of it. I thought the version is taken from `asset`.

**Comment by coherent-edkarhuber** [comment]
@Roblinde yes, it works, thanks!
