### ISSUE TITLE
Can't create Asset by using UploadReference

### ISSUE THREAD

**Issue by coherent-edkarhuber** [contentful/contentful.net#265]
Hello,

For some reason, I can't create assets by using UploadReference. Could you please assist?
Here is my code example (almost the same as in your [guide](https://www.contentful.com/developers/docs/net/tutorials/management-api/)):
```csharp
await using var stream = new MemoryStream();
await assetModel.AssetContent.CopyToAsync(stream);
var uploadReference = await _client.UploadFile(stream.ToArray());

// this comes from: https://www.contentful.com/developers/docs/net/tutorials/management-api/
// Set the properties that are not allowed to null to make sure they're not serialized with the request.
uploadReference.SystemProperties.CreatedAt = null;
uploadReference.SystemProperties.CreatedBy = null;
uploadReference.SystemProperties.Space = null;

var asset = new ManagementAsset
{
    SystemProperties = new SystemProperties
    {
        Id = "testuniqueid"
    },
    Title = new Dictionary<string, string>
    {
        { Entities.Locale.En, "create test asset" }
    },
    Description = new Dictionary<string, string>
    {
        { Entities.Locale.En, "some description" }
    },
    Files = new Dictionary<string, File>
    {
        {
            Entities.Locale.En, new File
            {
                ContentType = "image/png",
                FileName = "logo.png",
                UploadReference = uploadReference
            }
        }
    }
};

await _client.CreateOrUpdateAsset(asset);
```
I got the following error in the end:
```
Contentful.Core.Errors.ContentfulException: 'Validation error[
  {
    "name": "type",
    "type": "Link",
    "details": "linkType must be Upload",
    "value": {
      "sys": {
        "id": "3Woi6SHFhBsi9VxBW1glY8",
        "linkType": null,
        "type": "Upload",
        "revision": null,
        "version": null,
        "createdAt": null,
        "createdBy": null,
        "updatedAt": null,
        "updatedBy": null,
        "deletedAt": null,
        "locale": null,
        "contentType": null,
        "space": null,
        "publishedCounter": null,
        "publishedVersion": null,
        "publishedBy": null,
        "publishedAt": null,
        "publishCounter": null,
        "firstPublishedAt": null,
        "archivedAt": null,
        "archivedVersion": null,
        "archivedBy": null,
        "status": null,
        "environment": null,
        "organization": null,
        "usagePeriod": null
      }
    },
    "path": [
      "fields",
      "file",
      "en-US",
      "uploadFrom"
    ]
  }
]'
```

Even I specify `SystemProperties  LinkType = "Upload"` I still get the same exception.
Also I see ..."file", **"en-US"**, "uploadFrom"... but I use `en` as default locale for my space, only one `en` locale
![image](https://user-images.githubusercontent.com/46492587/142378007-c9057cbb-68e5-4068-9d64-eef9d0729aa7.png)
Version of `contentful.csharp`: **6.0.17**

Thanks.

**Comment by Roblinde** [comment]
hmm I'll have a look. I think the code looks good. Let me get back to you.

**Comment by Roblinde** [comment]
@coherent-edkarhuber turns out there's actually a line missing from the example. You need to set the properties to null (which is annoying) and you also need to set the linktype property to `"upload"`.

If you add the line: `uploadReference.SystemProperties.LinkType = "Upload";` just after setting the space to null I think it should work.

**Comment by coherent-edkarhuber** [comment]
@Roblinde 
> You need to set the properties to null
what do u mean? which properties should I set to `null`? UploadReference? could you provide an example, please?

Previously I've tried in that way:
```
uploadReference.SystemProperties.CreatedAt = null;
uploadReference.SystemProperties.CreatedBy = null;
uploadReference.SystemProperties.Space = null;
uploadReference.SystemProperties.LinkType = "upload";
```

and it didn't help me.
Thanks.

**Comment by coherent-edkarhuber** [comment]
@Roblinde never mind. All good. I tried to set LinkType to asset entity instead of uploadReference. 
It works in the way you suggested: `uploadReference.SystemProperties.LinkType = "Upload";`

Thanks again.
