### ISSUE TITLE
Question: Remove Render only have RenderAysnc from IContentRenderer or TableCellRenderer should use RenderAysnc

### ISSUE THREAD

**Issue by FreshRob** [contentful/contentful.net#266]
Hello,

Wonder what your thoughts were to removing Render completely and only having RenderAsync.

I noticed that in the HTMLRenderder it uses RenderAsync but things such as the new TableCellRenderer are using Render when rendering ContentRendererCollection this means Async calls for Renderers are being forced to be synchronous.

It would be good to get yours thoughts on this, obviously my suggestion of removing is a huge breaking change.

Edit: Added links + noticed it is any Renderer which calls the collection to render child items

RenderAsync in HTML Renderer
 https://github.com/contentful/contentful.net/blob/d84b23a07dde353bf4fb5be17183b5a84b52b8b5/Contentful.Core/Models/Authoring.cs#L85

TableCell
https://github.com/contentful/contentful.net/blob/d84b23a07dde353bf4fb5be17183b5a84b52b8b5/Contentful.Core/Models/Authoring.cs#L466

**Comment by Roblinde** [comment]
@FreshRob thanks for the suggestion. Yeah, now that I look at it it's an oversight on my part. All the rendering code is completely synchronous at the moment though, but if someone implemented some sort of asynchronous renderer (not sure what the use case here would be, maybe reading some info from another system?) it would indeed be forced to be synchronous.

The main reason I even added the async-methods were to more fluently support the `ProcessAsync` method of tag helpers.

It'd be fairly trivial to just move the render code into the asynchronous methods.

Do you have any use case where you would run some async code in a renderer currently?

**Comment by FreshRob** [comment]
From our code the only instance is that we use AngleSharp and we are using their ParseDocumentAsync, looking at it we could change it to be sync implemenation.

I guess the use case for async would be if someone wanted to do to a call to another api to get properties  that they required or a csharp service that was async like I had above.

Looking at the Taghelper in netcore github async is the source of truth. 

I will make a PR this weekend making it async and it is up to you if you would like it or not 😀

https://github.com/dotnet/aspnetcore/blob/30a18721e225241127c968e653662fbf810f39f7/src/Razor/Razor/src/TagHelpers/TagHelper.cs#L53

**Comment by FreshRob** [comment]
https://github.com/contentful/contentful.net/pull/268

**Comment by Roblinde** [comment]
Thanks @FreshRob! Your PR is now merged to version 7.0.0
