### ISSUE TITLE
Add tags to asset

### ISSUE THREAD

**Issue by FreshRob** [contentful/contentful.net#271]
I needed to add tags to an asset, to describe what type of asset it is.

I noticed tags were missing from the Asset and ManagementAsset models.

Created a pr https://github.com/contentful/contentful.net/pull/270

**Comment by Roblinde** [comment]
Thank you @FreshRob! I'll have a look.

**Comment by FreshRob** [comment]
Evening, were you able to look into it?

**Comment by Roblinde** [comment]
I was and have it merged and tested locally. Have just a few other things to add to the release, hopefully I'll get it out tomorrow.

**Comment by Roblinde** [comment]
Version 7.0.1 now out!
