### ISSUE TITLE
unexpected results with ContentfulClient.SyncInitial()

### ISSUE THREAD

**Issue by tele-bird** [contentful/contentful.net#273]
The ContentfulClient.SyncInitial() method returns **all** data when I pass it SyncType.All and a non-empty ContentType.  So essentially it ignores the ContentType I pass it.  Probably the _right_ fix is to honor the request and return the error that the endpoint returns: "When passing a content_type the type must be set to Entry.".
https://cdn.contentful.com/spaces/<space>/sync?initial=true&content_type=recipe

**Comment by Roblinde** [comment]
Hi @tele-bird 
This sounds like a good improvement. I don't know if it's necessary to actually pass through the request though, we can save a round trip and have a more descriptive error if we just throw if you've set `SyncType.All` and provided a content type.

I'll have a look at it.

**Comment by tele-bird** [comment]
@Roblinde , is Entry the only SyncType that allows to pass a non-empty ContentType to SyncInitial() ?

**Comment by Roblinde** [comment]
@tele-bird yes, only entries can have content types.

**Comment by Roblinde** [comment]
This should now be fixed in version 7.0.1

**Comment by tele-bird** [comment]
@Roblinde , would it be possible/desirable for the SDK to allow this kind of request for DeletedEntry as well?  It seems to me it would be very useful for maintaining a local cache for that specific content type.  If we want to cache only MyContentType, then we need to know whenever those entries are **changed** or **deleted**.  Otherwise, I'd need to sync all DeletedEntry, and then read through the entire list and ignore all the non-MyContentType ones.

The way the SDK works now, we'd need these two syncs:

1.  synctype = Entry AND contenttype = MyContentType
2. synctype = DeletedEntry AND contenttype = All

If the SDK were to allow DeletedEntry with a specific contenttype, then we could request a much more targeted sync for #2:

2. synctype = DeletedEntry AND contenttype = MyContentType

.. or maybe I'm missing the intended use?
