### ISSUE TITLE
Can't erase fields of entry by calling UpdateEntryForLocale method

### ISSUE THREAD

**Issue by coherent-edkarhuber** [contentful/contentful.net#274]
Hello,

Faced an issue when `null` values are ignored and not used to erase the current value of a field.
I have an entry with name, description (short text type), and other fields that are optional.
Contentful client ignores `null` values when I pass them, for example: `entry.Desription = null` (in case I want to remove the prev description value). I set `null` value, then call `UpdateEntryForLocale`, it returns me a successful response, but in the end, values are still there and not erased.
Code example that I tried:

```csharp
var companyEntry = _mapper.Map<Company>(company);
var updatedEntry = await _client.UpdateEntryForLocale(companyEntry, companyId);
```

or another one:
```csharp
var companyEntry = (await _client.GetEntriesForLocale(FilterById(companyId))).Items.First();

companyEntry.Name = null;

var updatedEntry = await _client.UpdateEntryForLocale(companyEntry, companyId);
```

Both give me the same result. If I pass `string.Empty` - all works, the previous value is replaced on an empty string, but the problem is that I can't publish it next because of validation. So I would expect to have `nulls` instead of empty strings.

Using contentful.csharp 6.0.17
Also tried with 7.0.0

**Comment by Roblinde** [comment]
Hi @coherent-edkarhuber this is by design for the `EntriesForLocale` endpoints. As the SDK can't know what type of object you pass in we safeguard by not deleting null values. You could use the slightly more involved endpoints "GetEntry" and "UpdateEntry".

Here's a very small example:
```
var entry = new Entry<dynamic>(); // Or get entry from Contentful
            entry.SystemProperties = new SystemProperties();
            entry.SystemProperties.Id = "new-thing";
          
            var jObject = new JObject(
                new JProperty("field1",
                    new JObject(
                        new JProperty("en-US", null))));

            entry.Fields = jObject;

            var newEntry = await _client.CreateOrUpdateEntry(entry, contentTypeId: id);
```

**Comment by coherent-edkarhuber** [comment]
I see. Ok, thanks.
