### ISSUE TITLE
Special characters being added to plain text

### ISSUE THREAD

**Issue by alexp1234** [contentful/contentful.net#281]
The problem we're having is very similar to https://github.com/contentful/contentful.py/issues/4 .
If a Contentful entry is created with plaintext values, it is possible to retrieve them without issue by this text value.
After some time, searching for entries by values no longer works, because special characters such as \u2014 are being added along with the plain text. I'm guessing that there is an issue deserializing from the cache, as when you simply edit the entry and resave, it begins to work for a time again.

**Comment by Roblinde** [comment]
Hi @alexp1234 This sounds interesting, I've never heard of this problem before. Could you show some code of how you're performing the search?

**Comment by alexp1234** [comment]
Thanks for the fast response, and yes certainly. I can't post exact code samples but it's a very simple logical process:

// This works for a time, but eventually stops working because "fields.something" value is retreived with special characters
var builder = new QueryBuilder<T>
builder = builder.FieldEquals("fields.something", my_value).ContentTypeIs("My_Content_Type");
ContentfulCollection<T> result = await client.GetEntries<T>(builder);

**Comment by Roblinde** [comment]
Have you tested running the same query directly against the api. Something like: https://cdn.contentful.com/spaces/SPACEID/entries?content_type=My_Content_Type&fields.something=my_value&access_token=xxx

I'm wondering if this is a .NET deserialization problem or a problem with the API response itself.

**Comment by alexp1234** [comment]
So I just tried running the query directly to retrieve all entries of a specific ContentType, and some of the data is showing up, but not all of it. I can clearly see the entries in the Contentful site, and they are the requested ContentType and are Published, so I'm not sure why they wouldn't be included in the response.

**Comment by Roblinde** [comment]
hmm that sounds even more suspicious... The default limit for the number of entries are 100, I don't suppose you're just running into that limit?

This feels like something we should maybe get someone from the Contentful API support team on.

**Comment by alexp1234** [comment]
Sorry my mistake, it appears I was running into that limit. When I query the API directly at the endpoint, everything looks fine
