### ISSUE TITLE
"force" delete support

### ISSUE THREAD

**Issue by coherent-edkarhuber** [contentful/contentful.net#282]
Hello,

Created this request to clarify "delete" behavior... Is it possible to "force" delete entry even it's in the `Published` state?
Looks like right now it's not possible - I receive "can't delete entry" exception. 
But there is nothing said about such requirement in documentation: https://www.contentful.com/developers/docs/net/tutorials/management-api/

> To permanently delete an asset.
`await client.DeleteAsset("<new_asset_id>", version);`

So could you confirm that I need at first `unpublish` and only then `delete` entry if it's in Published state?

Thanks

**Comment by Roblinde** [comment]
Hello @coherent-edkarhuber  yes, this is a limitation of the API, you cannot delete published assets. You'll notice the same behaviour in the web app. You need to first unpublish and then delete the asset.

Also note that even after deletion it may take some time for the asset to be removed from the CDN. Here's a snippet from the docs:

> Deleting an asset will remove the current asset and all previously referenced files on the CDN. It can take up to 48 hours until these files will be made unavailable from (assets|images|downloads|videos).ctfassets.net.

**Comment by coherent-edkarhuber** [comment]
the same is true for entries, right? I can't delete a published entry, correct?

**Comment by Roblinde** [comment]
Yes, that is correct.

**Comment by coherent-edkarhuber** [comment]
Thanks a lot
