### ISSUE TITLE
Fields are erased when call CreateOrUpdateEntry method

### ISSUE THREAD

**Issue by coherent-edkarhuber** [contentful/contentful.net#283]
Hello,
I have an issue with erasing data in Contentful when I'm trying to save the model which doesn't have all primitives fields (comparing with Contentful) by calling `CreateOrUpdateEntry` method.
To understand what I'm talking about lets assume:
1. In contentful we configure the model to have:
```
short text Name
short text Description
short text SomePrivate
integer Order
boolean IsActive
boolean IsVisible
```
2. In my .Net code I declare Model with only Name & Description, since Order and boolean flags are my internals in contentful.

3. And finally, when I pass my model with only `Name` & `Description` as Entry\<dynamic\> to `CreateOrUpdateEntry` method then other "private" fields are erased (set to default).

Is it by design or maybe I missed something and there is a way to partially update a model?

P.S. This issue is only about primitives fields. References or Links are not erased in such a case.

**Comment by Roblinde** [comment]
Hi @coherent-edkarhuber I believe the rest of the fields in this case are passed as null and therefore removed when you try to update the model.

I have added a method that could work for these scenarios though, if you try the `UpdateEntryForLocale` method I believe it will do what you want.

However, this method needs to make a couple of calls to the API behind the scenes. First it needs to call `GetEntry` to get the current entry from the API, then it call `GetContentType` for the content type of the entry to make sure it only sets the properties of fields that actually exist on the entry. It then finally calls `CreateOrUpdate` to actually update the entry.

If you want to do this more effectively you could use `GetEntry` and just update the correct fields with values from your object. Then call CreateOrUpdate to update the entry in Contentful.

Hope this helps.

**Comment by coherent-edkarhuber** [comment]
Thanks for the explanation

**Comment by coherent-edkarhuber** [comment]
Quick question:
you said
>I believe the rest of the fields in this case are passed as null and therefore removed when you try to update the model.

but is this ok if I don't pass them at all and they are still erased?
I build this Entry<dynamic> by myself instead of passing typed-model object. So again assume in the contentful we have a lot of properties, but in the code, I pass only several and all others are not declared at all (this means we don't pass null explicitly). 
So maybe the issue that SDK shouldn't use or set to null properties if they are not presented in input model, wdyt?

**Comment by Roblinde** [comment]
@coherent-edkarhuber this is a good idea in theory, but that would make it hard to actully do in practice as the underlying API will interpret a missing field as a null value and thus empty the field. This is basically the reason I added the `UpdateEntryForLocale ` method, it will only update the properties present in your model, but that unfortunately means a few excess calls :/

**Comment by coherent-edkarhuber** [comment]
@Roblinde got it, it's clear now. Thanks!
