### ISSUE TITLE
Unable to build Blazor WASM project using Contentful.AspNetCore

### ISSUE THREAD

**Issue by JamesIde** [contentful/contentful.net#285]
Hello,

Apologies if this is the wrong place to ask for help but I am not able to solve the problem at hand. I am trying to integrate contentful with my blazor web assembly application. I am using .net 6 and contentful.aspnetcore v 7.0.1.

I get the following error trying to build my application, this error seems to come from the following file:
portfolio\obj\Release\net6.0\portfolio.MvcApplicationPartsAssemblyInfo.cs

The error is the following:

```[assembly: Microsoft.AspNetCore.Mvc.ApplicationParts.ApplicationPartAttribute("Contentful.AspNetCore")]```

I can circumvent this error by simply removing the line of code from that class file, but after attempting to build my application on github workflows, I am greeted with the same error. Up until this point, it had been smooth as butter using contentful to store, edit and pull my images. My application is a standalone web assembly project and is not asp net core hosted so no server/shared projects. 

What could be done here? Am I to be using contentful.csharp for a blazor web assembly project?

Kind regards

**Comment by Roblinde** [comment]
Hi @JamesIde I'm not sure exactly what's causing the error, but the Contentful.AspNetCore package was built before Blazor was a thing so it might currently contain something that's not compatible. The contentful.csharp package should get you most of what you need though, the aspnetcore package is mostly some niceties for working with razor with some taghelpers, some middleware and some renderers for rich text. All of it should be fairly easy to replicate yourself if you need them in your Blazor app.

**Comment by JamesIde** [comment]
Hi @Roblinde. Thank you for your response. By moving to the contentful.csharp package, I was able to solve that problem. 
However, something else came to mind whilst I was doing that. By virtue of the ContentfulClient, the api keys that are requried to access the CDA are stored in appsettings.json. I'd like to avoid this as these keys could be visible to the user due to everything being done in the browser (once deployed). Is it possible to set up the ContentfulClient to use build environment variables that I could specify (in netlify, for example)and do you have any advice on how to achieve this?

**Comment by Roblinde** [comment]
Great!

Yes, you can absolutely user env variables for your contentfulclient. There are multiple constructors for the creation of the client. I'm not sure exactly how you wire the client up currently, but you can read from the env. variables and use an appropriate constructor when creating the actual client.

Something along the lines of: services.AddTransient<IContentfulClient>((sp) => new ContentfulClient(httpClient, envCDA, envCPA, envSpaceId));

**Comment by JamesIde** [comment]
Thanks @Roblinde. Worked like a charm. Only thing here was I had to create a web api component and query the Contentful CDA through that, then deserialise it to the client side because Blazor WASM applications cannot access environmental variables (AFAIK) so I could not securely store them. Thanks for the help, greatly appreciated!
