### ISSUE TITLE
Unable to save Rich Text field with BlockData

### ISSUE THREAD

**Issue by drachele** [contentful/contentful.net#290]
Hi,

There is an issue when trying to write to the Rich Text field when attempting to add BlockData content blocks.

The issue is in the `Contentful.Core.Models.BlockData` class. The `Target` property is the incorrect type.

It is currently: `ReferenceProperties`
It should be of type: `Reference`

This will make it match what the Contentful API is expecting, which is:

![image](https://user-images.githubusercontent.com/825135/164229650-45a55068-633a-4824-ad48-146443a77494.png)

Please can this change be made? I'm unable to save my content to Rich Text Editor currently.

Many thanks,
Dan.

**Comment by drachele** [comment]
Also, the `Block` class is missing `List<IContent> Content`

**Comment by Roblinde** [comment]
Thanks for the report @drachele I'll get this fixed. In the meantime you can always use a custom class (instead of BlockData) to get around it.

**Comment by drachele** [comment]
Hi @Roblinde 

Yes, I'm currently using my own custom class as a workaround, but would be good to get this fixed in the SDK at some point.

Thanks :)

**Comment by Roblinde** [comment]
Apologize for the delay, this should now be fixed in version 7.1.0
