### ISSUE TITLE
Quality parameter is discarded for webp images in ImageUrlBuilder

### ISSUE THREAD

**Issue by aKzenT** [contentful/contentful.net#293]
Expected: Quality parameter is passed on
Actual: It is removed

When using "q" parameters directly in the contentful image API with webp you see a visual difference between low and high settings. The doc also doesn't mention that it is not supported.

In the future it would probably make sense to rename the method also to make it clear that it is not only Jpg-Quality.

**Comment by aKzenT** [comment]
PR opened: https://github.com/contentful/contentful.net/pull/292

**Comment by Roblinde** [comment]
Thanks for the contribution! Fixed in version 7.1.0
