### ISSUE TITLE
Support ETag in SDK for improved caching

### ISSUE THREAD

**Issue by aKzenT** [contentful/contentful.net#294]
Contentful supports ETag/If-None-Match headers to deliver responses only when results have changed. Unfortunately there is no way to set/retrieve these headers in the .NET SDK.

A common scenario for these headers would be a local memory cache that stores some of the contentful responses in deserialized form. We want to regulary refresh this data every few seconds but we want to avoid spending CPU time and memory for deserializing for 99% percent of the cases where the data has not been changed.

To support this scenario I propose the following changes:
- Extend QueryBuilder with an IfNoneMatch method that accepts an ETag. Using this method the If-None-Match header is added to the request to contentful.
- On Receiving a 304 Not Modified HTTP Response, return null or an empty collection to the client
- In ContentfulCollection add an ETag propery to allow clients to store the ETag to use in subsequent queries

We might be able to contribute a PR for this feature if there is consensus if and how this feature can be supported.

**Comment by Roblinde** [comment]
This sounds interesting! I'll have look and get back to you.

**Comment by aKzenT** [comment]
I think adding a property to the client would be a bad idea for the reasons you outlines. It would not work for us at all as we reuse the contenful client where possible for multiple queries and the etag changes with every query. It would also make for an akward API where you would need to set a property on the client prior to calling the method you want.

So I think it has to be part of the method signature in some way. Adding it to the query builder seemed like a logical choice. Maybe the query builder in time could evolve to be a simple way to construct HttpRequests for contenful and not only providing query strings?

Regarding the return value I'm not sure whether an empty object or null would be preferable. I would however advise against throwing an exception as a "not modified" response would be a completely valid response and in fact the expected and preferred result and using exceptions for normal control flow is discouraged.

**Comment by Roblinde** [comment]
Hmm, yeah, I think maybe adding a parameter to all the get-functions would be the way to go.

What do you think about making it an out variable, being set to the returned e-tag value.

Would make the API Something like this:

```
var etag = "123";
var entries = GetEntries("some-query", out etag);
if (etag == "123") {
// entries are unchanged and would be null
}
else {
// E-tag has changed and need to be stored anew, entries would be deserialized into the correct returned structure.
}
```

**Comment by Roblinde** [comment]
Never mind, can't use out as it's async methods. Would have to find another way.

**Comment by Roblinde** [comment]
@aKzenT I think this is how I'd want to do it.

* Add an overload for each get-method that takes a new parameter `string etag`
* The new methods will return a tuple result (string etag, T Result)
* If the e-tags match the result will always be null, otherwise it will contain the result as normal.

Any thoughts on that?

**Comment by aKzenT** [comment]
@Roblinde In general this would work for us. Some thoughts however:

At least for the methods returning a ContentfulCollection, I would just add the Etag as a property on ContentfulCollection. It already has things like Limit and Skip, so I think it would be a good fit. It would also avoid polluting the API with tuple return types that do not really scale that well.

In fact, even for methods like GetEntry I would recommend creating a result class instead of returning a tuple. The last time I checked Microsoft discourages use of Tuples in public APIs. There is not much difference from returning a tuple or a custom class from a method from a consumer perspective and the custom class is easier to extend later on if you need to add other properties.

The "etag" string parameter is less of a problem from a design perspective in my opinion. However you could also consider creating a separate class for this additional property which might scale better if there are more properties you want to add in the future that are not part of the query parameters.

**Comment by Roblinde** [comment]
This should now be possible in 7.1 I decided to change into a result class for all endpoints that support e-tags. I did not add the e-tag to the ContentfulCollection, I felt a more uniform approach across all endpoints was better in this case.

**Comment by Roblinde** [comment]
Try it out and let me know what you think!

**Comment by aKzenT** [comment]
Hey,

I apologize for the late reply. I just had a look at the changes and I think it has everything we need. Thank you very much!

I didn't have the chance to try it on our productive system yet. If I encounter any problems, I'll let you know.

Thanks again!
