### ISSUE TITLE
QueryBuilder is hostile to re-use

### ISSUE THREAD

**Issue by rjgotten** [contentful/contentful.net#297]
`QueryBuilder` is currently excessively hostile to re-use.

There is no public way to create copies, neither via `ICloneable` nor via an explicit copy constructor.
You need to use reflection to copy over the protected `_querystringValues` storage.

Furthermore, the `QueryBuilder` does not allow overwriting existing query parameters with new values, e.g. once set a single time one can no longer change the `Limit` or `Skip` parameters. This makes use of the QueryBuilder to implement e.g. a method which does multiple queries over multiple offsets and stitches those together to work around the 1000 items per-request Contentful API limit, an absolute pain in the rear.

**Comment by Roblinde** [comment]
Hi @rjgotten 

Thanks for your suggestion.

The `QueryBuilder` isn't really meant to be reused, it is a convenient builder to produce a query string in the correct format the Contentful API:s expect.

For example, if you need to copy an existing query string you can just do `.Build()` on the `QueryBuilder` and copy the resulting string as you please.

If you need to overwrite parameters the easiest is probably to create a method similar to:

´´´
string GetQuery(int limit, int skip) {
return QueryBuilder.New.Limit(limit).Skip(skip).Build();
}
´´´

All methods in the SDK that takes a QueryBuilder also takes a string, in fact the SDK just calls `.Build()` under the hood to create the querystring.

**Comment by rjgotten** [comment]
@Roblinde 
The current design for `QueryBuilder` makes it impossible to create further abstractions that use `QueryBuilder` as an argument and require that it pre-process before actually dispatching a query. I already cited one such case: a `GetTotalEntries` which has to perform queries with different offsets serially and then stitch the results back together:

```cs
/// <summary>
/// Gets all entries of a space, filtered by an optional <see cref="QueryBuilder{T}"/>
/// using multiple result sets if need be, abstracting over the limit on returned
/// entries per request of the Contentful API.
/// </summary>
/// <typeparam name="T">
/// The class to serialize the response into. If you want the metadata to be included
/// in the serialized response use the <see cref="Entry{T}"/> class as a type parameter.
/// </typeparam>
/// <param name="client">The current <see cref="IContentfulClient"/>.</param>
/// <param name="queryBuilder">The <see cref="QueryBuilder{T}"/> to add additional filtering to the query.</param>
/// <param name="cancellationToken">The optional cancellation token to cancel the operation.</param>
/// <returns>A <see cref="ContentfulCollection{T}"/> of items.</returns>
/// <exception cref="ContentfulException">There was an error when communicating with the Contentful API.</exception>
public static async Task<ContentfulCollection<T>> GetTotalEntries<T>(
  this IContentfulClient client,
  QueryBuilder<T> queryBuilder,
  CancellationToken cancellationToken = default
)
```

This is in keeping with the pattern of passing a `QueryBuilder<T>`.
What you are suggesting is that rather than passing a `QueryBuilder<T>` , such methods would have to pass a factory function, i.e. `Func<QueryBuilder<T>>` that can create the query up to a certain point; and then the method itself can finalize things by adding e.g. the `.Limit()` and `.Offset()` calls.

However, even that design is flawed, because nothing prevents a consumer from already having _set_ a limit and/or offset inside that factory function; at which point the basic logic of such an extension method fails - because once set, a parameter cannot be changed anymore. So really, you'd need an `Action<QueryBuilder<T>>` which pre-sets the limit and offset in this case. Which is just ... awfully inelegant code and completely breaks API parity with the built-in APIs.
