### ISSUE TITLE
Newtonsoft 13 - Maxdepth error

### ISSUE THREAD

**Issue by FreshRob** [contentful/contentful.net#300]
When Querying Contentful the json can be large and therefore causing Newtonsoft 13 to throw an exception as it excedes the 64 depth limit.

I've [raised a pr to fix this issue](https://github.com/contentful/contentful.net/pull/299)

error in question 

`Newtonsoft.Json.JsonReaderException: 'The reader's MaxDepth of 64 has been exceeded. Path 'items[0].content.content.content[54].content[0].content[0].content[0].data.target.internalPage.content.content.content[57].content[1].content[0].content[1].data.target.internalPage.content.content.content[53].content[2].content[0].content[1].data.target.internalPage.content.content.content[54].content[3].content[0].content[0].data.target.internalPage.content.content.content[46].content[0].content[0].content[0].marks', line 30654, position 36.'`

More information on the issue is on [this stackoverflow page](https://stackoverflow.com/a/68580426)

**Comment by Roblinde** [comment]
Fixed in version 7.2
