### ISSUE TITLE
Sync API and UsePreviewApi

### ISSUE THREAD

**Issue by trametheka** [contentful/contentful.net#304]
Hi,

Wondering about Preview API support with SyncInitial/SyncNextResult.

According to the following, it is a limitation that Preview API is not supported with the Sync API - https://www.contentful.com/developers/docs/references/content-preview-api/#/introduction/preview-api-limitations

However, the code is implemented in this library, and switching UsePreviewAPI to true and setting a PreviewAPIKey works. The initial sync pulls everything including Draft content, and SyncNext will correctly pull only changes.

Going forward, we would appreciate this be supported and continue to work, however we can't rely on something that might break tomorrow if it's not.

Is this intended behaviour and can we rely on it to keep working?

Cheers!

**Comment by Roblinde** [comment]
Hi @trametheka 

I'm afraid I don't have any official information if this is intended or not, but I have dropped the question in the Contentful slack and will hopefully get a reply there.

**Comment by Roblinde** [comment]
Turns out this works, but seems to not be intended. I don't know for how long it will work or if it'll be changed at any moment. I would not rely on this functionality.

**Comment by Seth-Carter** [comment]
Just a quick update on this for clarity:

We have no plans to deprecate or remove the preview sync API. 

It is currently being maintained as status quo. So if a customer has an implementation that relies on this then they can continue to use it without worrying that we're going to remove it. 

We do have improvements to the sync and preview APIs on our long-term roadmap, but for now it will continue to work as it currently does.

**Comment by Roblinde** [comment]
@Seth-Carter thanks for the clarification!
