### ISSUE TITLE
Assets returning null for some entries but not others, even when published.

### ISSUE THREAD

**Issue by RAGrundy** [contentful/contentful.net#308]
Hi,

I've been setting up a call to contentful to retrieve some entries which have Assets I need to retrieve. The issue is for some of the entries, even though the Assets are published, these are not coming through.

I am using contentful.csharp Version 7.2.3

My content model is as follows:
![image](https://user-images.githubusercontent.com/29862271/225573291-c6aec7f5-a91f-44d5-81ba-601e8ba9878a.png)

My C# class is as follows (I have only a subset of the fields as these are all I need currently):
```
public class ContentfulProduct 
{
    public SystemProperties Sys { get; set; }
    public string ProductName { get; set; }
    public List<ContentfulCategory> Categories { get; set; }
    public string Slug { get; set; }
    public string ProductDescription { get; set; }
    public Asset Image { get; set; }
}

public class ContentfulCategory
{
    public string Name { get; set; }
}
``` 

And I call get entries as follows:
```
var query = new QueryBuilder<ContentfulProduct>().ContentTypeIs("productPage").Limit(200);
var items = await _contentfulClient.GetEntries<ContentfulProduct>(query);      
```

When I inspect items in the debugger I can see the Image Asset as null for some, but not others, and there is no difference in contentful that I can tell. This has happened for 4 of the 29 entries I have returned

![image](https://user-images.githubusercontent.com/29862271/225574368-3cf425d1-db7c-452c-8446-22f372193874.png)

It is published in contentful:
![image](https://user-images.githubusercontent.com/29862271/225576178-41e68c2c-62ec-4029-a167-64168ad94feb.png)

The asset and containing entry are also published.

I can even see it in the IncludedAssets (I have hidden the description and title, but this record marries up to the one I expect to see):
![image](https://user-images.githubusercontent.com/29862271/225576535-9bfc72a5-3f41-4745-bbda-fac83bd26069.png)

If you could give me any pointers where to look if it could be my mistake, or a way to get around this for now that would be really helpful.

Thanks,
Robert.

**Comment by Roblinde** [comment]
Hi @RAGrundy 

This is usually because of some shenanigans that needs to happen when deserializing content that doesn't include all fields as properties of the objects. I wrote about it here: https://robertlinde.se/posts/why-is-my-item-null-contentful-net/

Hope this helps you out!

**Comment by RAGrundy** [comment]
HI @Roblinde 

Thanks, so much for this response, that is exactly what was happening, and the suggestion to use ResolveEntriesSelectively worked a treat. Thanks for linking the Article you wrote, that was really useful for understanding the why also.

Thanks,
Rob.
