### ISSUE TITLE
Is there a way to setup a default IContentTypeResolver?

### ISSUE THREAD

**Issue by kruncher** [contentful/contentful.net#311]
I am using the AddContentful() method to setup the various services. Is there a way to define the `IContentTypeResolver` on the service container?

**Comment by Roblinde** [comment]
Hi @kruncher 

There's no way in the actual `AddContentful` call to add a resolver, but you could easily make your own call to add the client, something like this:

```
services.TryAddTransient<IContentfulClient>((sp) => {
                var options = sp.GetService<IOptions<ContentfulOptions>>().Value;
                var factory = sp.GetService<IHttpClientFactory>();
var ctflClient = new ContentfulClient(factory.CreateClient(HttpClientName), options);
ctflClient.ContentTypeResolver = new YourMagicResolver();
                return ctflClient;
            });

```

**Comment by kruncher** [comment]
That sounds like a sensible approach; thank you 😊
