### ISSUE TITLE
ContentfulClient GetEntries not resolving entries sub props objects correctly in certain scenario

### ISSUE THREAD

**Issue by stephenlautier** [contentful/contentful.net#312]
We found an issue where the `ContentfulClient.GetEntries` is not resolving the entries correctly for its sub properties when they are other references.

I believe this is the scenario which is causing it:

The following are entries which have other entries (not of the same type), something like this:

```
// issue occurs only when returning multiple results (in this case 2)
A -> B -> C
X -> Y -> A

// when querying 1 by 1 it works fine e.g. either
A -> B -> C
OR
X -> Y -> A
```

Our entity is something like this (simplified)

```cs
public class WidgetPlaceholderGroup {
   public SystemProperties Sys { get; set; }
   public List<WidgetPlaceholder> Placeholders {get;set}
}

public class WidgetPlaceholder {
   public SystemProperties Sys { get; set; }
   public ContentfulEntity Content {get;set}
}
```

Whats happening the `Placeholders` inside the `WidgetPlaceholderGroup` is returning `null` entries from the `client.GetEntries`, inside the `.Items` (see screenshot)

![image](https://github.com/contentful/contentful.net/assets/3908723/c9a33130-cf9e-4983-aeb4-8b90e7d5a685)

Again this only seems to happens if we query another related entity (in this case `A + X`)

From our debugging this seems to happen when the [entries](https://github.com/contentful/contentful.net/blob/master/Contentful.Core/ContentfulClient.cs#L263) are being built, and cause only when converted (manually) to `$refs` possibly [this](https://github.com/contentful/contentful.net/blob/master/Contentful.Core/ContentfulClient.cs#L364)

**Comment by Roblinde** [comment]
Hi @stephenlautier 
have you had a look at this post:  https://robertlinde.se/posts/why-is-my-item-null-contentful-net/ ?
It explains a bit of the deserialization process and highlights some cases in which an item might be returned as null.

**Comment by stephenlautier** [comment]
It seems it fixes it, tho to be fair it seems more like a bug to me 👀 

From what i understand its storing the object when the `$ref` the incorrect one, cause there is the data correctly in the response and in the items, but after processing before deserializations its being converted to `$ref` in the items, and not resolved prior that

![image](https://github.com/contentful/contentful.net/assets/3908723/13800710-d1c8-458c-9d0f-cc3b8d5accb8)

**Comment by stephenlautier** [comment]
Something like this what i have in mind, would it make sense? (tho this is not working currently nor polished)

```cs
var refs = json.SelectTokens("$.items..$ref");
foreach (var item in refs)
{
    var id = item.Value<string>();
    // todo: cache id => token
    // todo: handle assets
    var includeEntry = json.SelectToken($"$.includes.Entry[?(@.sys.id=='{id}')]");
    // todo: replace properly
    if (includeEntry != null)
        item.Parent.ReplaceAll(includeEntry);
}

entries = json.SelectToken("$.items").ToObject<IEnumerable<T>>(Serializer);
```
Would something similar be good?

**Comment by Roblinde** [comment]
Great, glad it's working!

This is a direct causation by how json.net handles deserialization. If a property is not present in the structure that you deserialize into it will be forgotten. The way it's handled now is by inspecting the object structure through reflection and handling any properties that are not deserialized. The $ref is an internal structure to json.net.
