### ISSUE TITLE
No field with id "sys" found

### ISSUE THREAD

**Issue by himynameistim** [contentful/contentful.net#315]
I can create a record using client.createEntry but if I try updating an entry using CreateOrUpdateEntry whatever I try results in an exception Contentful.Core.Errors.ContentfulException: 'No field with id "sys" found.

<img width="855" alt="image" src="https://github.com/contentful/contentful.net/assets/5212530/fc636174-e84a-4637-9700-d833d58a8d5d">

Even getting an object from contentful using GetEntriesCollection taking the first and sending it back results in the same error.

**Comment by Roblinde** [comment]
Hi @himynameistim 

I think what happens here is that the sys property is accidentally being passed as part of the fields object. 

Could you share a snippet of the code? I should be able to point out the fix easily.

**Comment by himynameistim** [comment]
Thanks you were correct. My object included public SystemProperties Sys { get; set; }
