### ISSUE TITLE
How the use the .Net SDK to create and entry?

### ISSUE THREAD

**Issue by kim-petersen-akqa** [contentful/contentful.net#317]
I would like to use the ContentfulManagementClient in the .Net SDK to create and update entries in Contentful.
I really do not want to use dynamic for this, as I prefer strongly typed classes.

However I get this error when calling CreateEntry:
```
No field with id "sys" found.[
  {
    "name": "unknown",
    "path": [
      "fields",
      "sys"
    ]
  }
]
```

The object I send in is:
```
public class MyProduct
{
    public EntrySys? sys { get; set; }
    public IDictionary<string, string>? description { get; set; }
    public IDictionary<string, string>? name { get; set; }
}
```

I could remove the "EntrySys" from my class, however then I do not get the "sys" back from the create, and I then do not know what the id and version of the entry is.

I have the same issue on update, using the CreateOrUpdateEntry method.

The issue seems to be the way you have created the CreateEntry. You take my type and put it in the Fields of and Entry<object> class, but when you return it, you only gives me the object back. 
I think that if you returned Task<Entry<T>> instead of Task<T>, then the classes for input and output would be the same, and I will get the sys properties in the Entry.

Hope you can help :)

**Comment by Roblinde** [comment]
Hi @kim-petersen-akqa 

Take a look at the `CreateEntryForLocale` and `UpdateEntryForLocale` methods. In the case you don't need to create entries with multiple different field values in different locales they do pretty much what you're asking for here.

**Comment by kim-petersen-akqa** [comment]
I need to add multiple locales as it is an import.
But even if I could use `CreateEntryForLocale` and `UpdateEntryForLocale` methods, they return a dynamic, and not a strongly typed class.

Could you please provide me with a simple code example on how to use this method, where input and output is a strongly typed class and where you can get the `id` and `version` of the created entry: `public async Task<T> CreateOrUpdateEntry<T>(T entry, string id, string spaceId = null, string contentTypeId = null, int? version = null, CancellationToken cancellationToken = default(CancellationToken))`

I can see that other developers are also struggling with this, so I think it will help to get an example.

Thanks in advanced for the code example :)

**Comment by Roblinde** [comment]
All of the methods to manage entries in the SDK are using `Entry<dynamic>`. I guess the easiest way for you in this scenario would be something like this:

`
var myProduct = new MyProduct(); // set all the values

var entryToCreate = new Entry<dynamic>();
entryToCreate.SystemProperties = new SystemProperties { Id = myProduct.sys.id};
entryToCreate.Fields = new { myProduct.description, myProduct.name ...  }

var createdEntry = CreateOrUpdateEntry(entryToCreate, contentTypeId: "content-type");

// for subsequent calls use createdEntry.SystemProperties.Version and Id where appropriate.

`

You still have your strongly typed `MyProduct` which contains all the correct values, but you also get the `SystemProperties` that you need from Contentful for publishing the entry  for example.

**Comment by kim-petersen-akqa** [comment]
Work around is to use dynamic :(
