### ISSUE TITLE
.NET 6.0 support

### ISSUE THREAD

**Issue by kavitap081** [contentful/contentful.net#319]
Hi,
I am using contentful.net with my Xamarin.Forms application to interact with Contentful system, and it is working fine. But soon, we will be migrating to .NET MAUI. In your documentation, I do not see that even the latest version is supporting .NET 6.0.

Can you please confirm what is the plan to support .NET 6.0? So, that we can plan to migrate to. MAUI.

**Comment by Roblinde** [comment]
Hi @kavitap081 The idea is to support .NetStandard 2.0 which means it should work fine with .Net 6.0. See https://learn.microsoft.com/en-us/dotnet/standard/net-standard?tabs=net-standard-2-0

Let me know if there are any problems.
