### ISSUE TITLE
How to load more than 10 levels using contentful api?

### ISSUE THREAD

**Issue by RaduTudorIon** [contentful/contentful.net#323]
According to documentation ("the maximum number of levels is 10. The API will throw a BadRequestError for higher values or values other than an integer. The default number, if the parameter is not specified, is 1. To omit linked items, specify include as 0." (https://www.contentful.com/developers/docs/references/content-delivery-api/#/reference/links). But in contentful there is no such limit, so what do you do if you have 11 levels and want to load them all without getting the broken link error?

**Comment by Roblinde** [comment]
HI @RaduTudorIon 

Thank you for the question.  I'm not sure what you mean by `in contentful there is no such limit`. This is a limitation of the underlying API and not the SDK.

If you need further levels of content you will have to separate this into multiple requests to the API.

Hope this helps.
