### ISSUE TITLE
Validation error When creating an entry with hyperlink in rich text content.

### ISSUE THREAD

**Issue by arekkondratiuk** [contentful/contentful.net#325]
I'm trying to create content that has a hyperlink inside a paragraph. The test data created directly in the Contentful Rich Text editor is returned as:

{
        "nodeType": "paragraph",
        "data": {},
        "content": [
          {
            "nodeType": "text",
            "value": "Paragraph with ",
            "marks": [],
            "data": {}
          },
          {
            "nodeType": "hyperlink",
            "data": {
              "uri": "https://www.google.com/"
            },
            "content": [
              {
                "nodeType": "text",
                "value": "link to Google",
                "marks": [],
                "data": {}
              }
            ]
          },
          {
            "nodeType": "text",
            "value": " inside text.",
            "marks": [],
            "data": {}
          }
        ]
      },

and rendered to the HTML as:

`<p>Paragraph with <a href="https://www.google.com/" title="">link to Google</a> inside text.</p>`

I tried to create the same thing from the C# code. When I call CreateOrUpdateEntry method from IContentfulManagementClient, it returns a validation error, as follows:
Contentful.Core.Errors.ContentfulException: Validation error[
  {
    "name": "unexpected",
    "details": "The property \"title\" is not expected",
    "path": [
      "fields",
      "content",
      "en-US",
      "content",
      8,
      "content",
      1,
      "data",
      "title"
    ]
  }
]
   at Contentful.Core.ContentfulClientBase.CreateExceptionForFailedRequest(HttpResponseMessage res)
   at Contentful.Core.ContentfulClientBase.EnsureSuccessfulResult(HttpResponseMessage response)
   at Contentful.Core.ContentfulClientBase.SendHttpRequest(HttpRequestMessage request, CancellationToken cancellationToken)
   at Contentful.Core.ContentfulClientBase.SendHttpRequest(String url, HttpMethod method, String authToken, CancellationToken cancellationToken, HttpContent content, Nullable`1 version, String contentTypeId, String organisationId, List`1 additionalHeaders)
   at Contentful.Core.ContentfulManagementClient.PutAsync(String url, HttpContent content, CancellationToken cancellationToken, Nullable`1 version, String contentTypeId, String organisationId, List`1 additionalHeaders)
   at Contentful.Core.ContentfulManagementClient.CreateOrUpdateEntry(Entry`1 entry, String spaceId, String contentTypeId, Nullable`1 version, CancellationToken cancellationToken)
   at Contentful.Core.ContentfulManagementClient.CreateOrUpdateEntry[T](T entry, String id, String spaceId, String contentTypeId, Nullable`1 version, CancellationToken cancellationToken)

Here is how looks the data structure passed to the management client:
![image](https://github.com/contentful/contentful.net/assets/110888353/4208ecf1-d6ca-4be2-9430-ace0e1975053)

A firts I tried to pass the Title value if it was specified in the link, but even when I pass null value, the API throws an error.

I checked what the CreateOrUpdateEntry method looks like. My guess is that the problem is in the `Contentful.Core.Extensions.JsonConversionExtensions.ConvertObjectToJsonString(this object ob)` method.
Here we have:

`var settings = new JsonSerializerSettings
{
    ContractResolver = resolver,
};`

The `settings.NullValueHandling` is set to a default `NullValueHandling.Include`.

Perhaps, setting this to the `NullValueHandling.Ignore` will solve the problem, but I'm not sure how this would affect other usings of this mehtod (i.e. how API will respond to the GenericStructureData without Target property).

**Comment by Roblinde** [comment]
Hi @arekkondratiuk

Thank you for the detailed error report. What class are you using to create the Hyperlink within the rich text structure in this case?

**Comment by arekkondratiuk** [comment]
Hi @Roblinde 
I'm using my own class, which creates a Contentful.Core.Models.HyperLink. For my client I'm creating something similar to the HtmlRenderer (HtmlParser in this case) which converts Html from TinyMce (input value is generated using Contentful.Core.Models.HtmlRenderer) to the Contentful Document using AngleSharp library. 
Here is the implementation of my HyperlinkConverter:

```
public class HyperlinkConverter : ContentConverterBase, IHtmlContentConverter
{
    private const string NodeType = "hyperlink";
    private const string NoUriHref = "about:///#";
    
    public HyperlinkConverter(HtmlContentConverterCollection converterCollection) 
	: base(converterCollection)
    {
    }

    // <inheritdoc />
    public int Order { get; set; } = 100;

    // <inheritdoc />
    public bool SupportsNode(INode node) => node is IHtmlAnchorElement;

    // <inheritdoc />
    public IContent ToContent(INode node)
    {
        var anchorElement = node as IHtmlAnchorElement;

        if (anchorElement is null)
        {
            throw new ArgumentException("Not IHtmlAnchorElement", nameof(node));
        }

        if (string.IsNullOrWhiteSpace(anchorElement.Href) || string.IsNullOrWhiteSpace(anchorElement.TextContent))
        {
            return PlainTextConverter.CreatePlainTextContent(anchorElement.TextContent);
        }

        var uri = anchorElement.Href == NoUriHref ? "#" : anchorElement.Href;
        
        var hyperlink = new Hyperlink()
        {
            NodeType = NodeType,
            Data = new HyperlinkData { Uri = uri },
            Content = new List<IContent>(),
        };
        
        if (node.ChildNodes.Length == 0)
        {
            hyperlink.Content.Add(PlainTextConverter.CreatePlainTextContent(node.TextContent));
            return hyperlink;
        }
        
        hyperlink.Content.AddRange(ConvertChildNodes(node));
        return hyperlink; 
    }
}
```

and the ConvertChildNodes from base class

```
protected List<IContent> ConvertChildNodes(INode element)
{
    var innerContent = new List<IContent>();

    foreach (var childNode in element.ChildNodes)
    {
        var parser = _converterCollection.GetConverterForNode(childNode);

        if (parser is not null)
        {
            innerContent.Add(parser.ToContent(childNode)); 
        }
    }
    
    return innerContent;
}
```

and CreatePlainTextContent from PlainTextConverter:

```
public static IContent CreatePlainTextContent(string value) => new Text
{
    NodeType = ContentNodeType,
    Value = value,
    Data = new GenericStructureData(),
    Marks = new List<Mark>(),
};
```

Right now I have a support for <p> (Paragraph) <b>, <strong>, <em>, <i>, <u> (Text with Marks), <ul>, <ol> (List), <li> (ListItem), <h1 - h6> (Heading1-6). 
So far, everything works fine, but I have a requirement to add the support for Hyperlinks.

**Comment by Roblinde** [comment]
@arekkondratiuk Sorry for the delay. Version 7.5 is now out and should resolve this. Simply leave title as null and it should no longer be included in serialization.
