### ISSUE TITLE
Missing generic implementation from UpdateEntryForLocale() as described in the official documentation.

### ISSUE THREAD

**Issue by pjmlp** [contentful/contentful.net#327]
According to the documentation, `UpdateEntryForLocale()` is supposed to have a generic version.

https://www.contentful.com/developers/docs/net/tutorials/management-api/

Pasting here the example from the documentation,

```csharp
var product = new Product();
product.Title = "Fidget spinner";

await client.UpdateEntryForLocale<Product>(product, id: "abc123", locale: "en-US");
//locale will default to the default locale of the space, which means you can omit it if you're setting values for the default locale.
```

However I can only find the non-generic version of the method in this repo.

![image](https://github.com/contentful/contentful.net/assets/608876/de4275a6-025a-4c65-91b4-a522b89b0a4d)

**Comment by Roblinde** [comment]
Hi @pjmlp 

That's a copy paste mistake in the documentation. Thanks for pointing it out. 

It would be fairly easy to add a generic version though. Do you have a need for it?

**Comment by pjmlp** [comment]
I ended up using `CreateOrUpdateEntry()` instead, as some other stuff was failing on me.

In general, I feel the .NET documentation could be better, not only in regards to `UpdateEntryForLocale()`.

There is some need to dive into the REST documentation and then try to guess how it actually maps to the SDK, just as side remark, as it unrelated to the ticket.

**Comment by Roblinde** [comment]
It definitely could be better. 

UpdateEntryForLocale alsp uses CreateOrUpdateEntry behind the scenes. If you wanna have a glance at the implementation:

```
var entryToUpdate = await GetEntry(id, spaceId);
            var contentType = await GetContentType(entryToUpdate.SystemProperties.ContentType.SystemProperties.Id, spaceId);
            var allFieldIds = contentType.Fields.Select(f => f.Id);

            if (string.IsNullOrEmpty(locale))
            {
                locale = (await GetLocalesCollection(spaceId, cancellationToken)).FirstOrDefault(c => c.Default).Code;
            }

            var jsonEntry = JObject.Parse(entry.ConvertObjectToJsonString());
            var fieldsToUpdate = (entryToUpdate.Fields as JObject);

            foreach (var fieldId in allFieldIds)
            {
                if (jsonEntry[fieldId] != null)
                {
                    if (fieldsToUpdate[fieldId] == null)
                    {
                        fieldsToUpdate.Add(fieldId, new JObject(new JProperty(locale, null)));
                    }

                    fieldsToUpdate[fieldId][locale] = jsonEntry[fieldId];
                }
            }

            var updatedEntry = await CreateOrUpdateEntry(entryToUpdate, spaceId: spaceId, version: entryToUpdate.SystemProperties.Version, cancellationToken: cancellationToken);

            return updatedEntry;
```
 
As you can see it's quite iniefficient as multiple calls are needed to get the fields from the content type to make sure only the correct ones are updated etc.
        
 It's probably best to write a more targeted implementation yourself, like you've done.
