### ISSUE TITLE
ContentfulManagementClient.UploadFileAndCreateAsset fails

### ISSUE THREAD

**Issue by msm-agyemang** [contentful/contentful.net#328]
This used to work 3 days ago without a hitch. Since yesterday (5th March 2024), code which previously uploaded a file and created an asset is failing with a validation error.

`[
        {
          "name": "unknown",
          "path": [
            "fields",
            "file",
            "en-US",
            "uploadFrom",
            "sys",
            "environment"
          ],
          "value": {
            "sys": {
              "id": "master",
              "linkType": "Environment",
              "type": "Link",
              "revision": null,
              "version": null,
              "createdAt": null,
              "createdBy": null,
              "updatedAt": null,
              "updatedBy": null,
              "deletedAt": null,
              "locale": null,
              "contentType": null,
              "space": null,
              "publishedCounter": null,
              "publishedVersion": null,
              "publishedBy": null,
              "publishedAt": null,
              "publishCounter": null,
              "firstPublishedAt": null,
              "archivedAt": null,
              "archivedVersion": null,
              "archivedBy": null,
              "status": null,
              "environment": null,
              "organization": null,
              "usagePeriod": null
            }
          },
          "details": "The property \"environment\" is not allowed here."
        }
      ]`

UploadFileAndCreateAsset calls UploadFile method. I believe the UploadFile method now sets the SystemProperties.Environment property and this is what is causing the issue. 

The fix I believe will be to set it back to null after the call to UploadFile
`uploadReferefence.SystemProperties.Environment = null;`

Have raised PR
https://github.com/contentful/contentful.net/pull/329

**Comment by Roblinde** [comment]
@msm-agyemang there's been no releases the last couple of days. It feels weird that it should just start failing. I am not aware of any changes to the underlying api.

**Comment by msm-agyemang** [comment]
You are right @Roblinde. Have even downgraded to 7.4.2 and yet still, same error. What I suspect is either Contentful has changed such that it sets the Environment property in its response or it is now validating against when it is being set.

Have tried with setting Environment to null and though it doesn't return a validation error, the asset seems to not get processed.

So at this point, I've had to raise a support ticket to find out if there is a problem in my Contentful space that I do not yet know of.

**Comment by Roblinde** [comment]
Or wait, I can't do that now that I look at it. The environment needs to be set if you're actually working with environments... not sure what's going on here. Let me know if you get some feedback on your ticket. @msm-agyemang

**Comment by msm-agyemang** [comment]
Sure. Will let you know if I get any feedback from Support

**Comment by msm-agyemang** [comment]
Hi @Roblinde. This is the response I got from Contentful support

_Hi Kojo,
Richard here from engineering.
Hope you are well and apologies for the inconvenience you are experiencing with the SDK.
As you have noticed, the response returned from our upload API was changed to now include an environment object and the SDK has not yet been updated to align with these changes.
I am working on getting a timeline for when it will be updated, in the meantime, the fix you implemented initially should work now without
any timeout errors (i.e. manually setting the Environment property to null) before triggering the processing.
Apologies again, and we will keep you informed of when we expect the SDK to be adjusted.
Kind regards,
Richard_

**Comment by Roblinde** [comment]
@msm-agyemang interesting! I'll get the SDK updated as soon as I get a chance!

**Comment by Roblinde** [comment]
@msm-agyemang Thanks for the help with this. I've now released version 7.5.1 that hopefully handles this.

**Comment by MatthewVisser** [comment]
Hello,
I'm getting the same error message when calling client.UploadFileAndCreateAsset
I'm using **contentful.csharp** and not the **contentful.aspnetcore** version in my Unity project.
Are there any plans to fix this version?
I haven't been able to get the workaround to work for me, I've tried setting 
managementAsset.SystemProperties.Environment = null; 
in a few different places.

**Comment by Roblinde** [comment]
@MatthewVisser Hi Matthew the fix was implemented in the core project and should affect both .csharp and .aspnetcore, unless I've done something truly weird. Are you running the latest version?

**Comment by MatthewVisser** [comment]
Sorry about that, the issue was on my end. I reinstalled my NuGetForUnity and have the latest version of the Contentful sdk now and its working.

**Comment by Roblinde** [comment]
Glad to hear it!
