### ISSUE TITLE
Update TableCell Data field to be TableCellData object instead of GenericStructureData

### ISSUE THREAD

**Issue by msm-agyemang** [contentful/contentful.net#330]
The **TableCell** class has a **Data** property which currently is of type **GenericStructureData**. This does not allow the **rowspan** and **colspan** fields from being serialized/deserialized from/to Contentful.

I can workaround writing by creating a TableCellData class that inherits from GenericStructureData but I can't deserialize.

If a TableCellData class can be created with these 2 properties and the TableCell.Data property updated to be of type TableCellData, then that should solve the problem

**Comment by Roblinde** [comment]
Ah interesting, I'll look into adding these. Thanks for the report.

**Comment by msm-agyemang** [comment]
Any updates on this? I could raise a PR for this if need be

**Comment by Roblinde** [comment]
@msm-agyemang a PR is always appreciated! I'm abroad a couple of days now, but hopefully I can have a look beginning of next week.

**Comment by msm-agyemang** [comment]
PR created https://github.com/contentful/contentful.net/pull/331

**Comment by Roblinde** [comment]
@msm-agyemang a new package was now released including these changes. Thanks for the contribution!
