### ISSUE TITLE
Hardcoded base URL problematic for EU data residency

### ISSUE THREAD

**Issue by jtlehtinen** [contentful/contentful.net#335]
The base URL is hardcoded in https://github.com/contentful/contentful.net/blob/master/Contentful.Core/ContentfulClient.cs#L26.
This makes the usage of the library problematic for those who have a Premium plan with EU data residency. As described in https://www.contentful.com/developers/docs/infrastructure/eu-data-residency/#for-apis
the base URL must be `https://cdn.eu.contentful.com/spaces/` in this case and not the hardcoded one.

We can workaround this by e.g. rewriting the request URI. But, it would be nice if this library provided a configuration option to
specify the host in a similar way the JavaScript library does https://github.com/contentful/contentful.js/blob/master/lib/contentful.ts#L46.

**Comment by Roblinde** [comment]
Hi @jtlehtinen 

I've just released version 7.5.3 where there is a public `BaseUrl` property on the `IContentfulClient`
