### ISSUE TITLE
ContentfulManagementClient.GetContentTypesAsync throws InvalidCastException when a field uses MimeTypeValidator

### ISSUE THREAD

**Issue by mgrzyb** [contentful/contentful.net#40]
MimeTypeValidator only supports single MimeType while admin UI and API use an array of mime types. This leads to ValidationsJsonConverter to throw when trying to deserialize an array of mime types into a string (single mime type).

**Comment by Roblinde** [comment]
You're quite right! I'll fix that asap.

**Comment by Roblinde** [comment]
It turns out the API can sometimes return a single value, but most oftenly it returns it as an array. I will update the SDK to handle both cases appropriately. Unfortunately this is a breaking change, but a new version will be out shortly.

**Comment by Roblinde** [comment]
This should now be fixed in contentful.csharp 0.11.0-beta and contentful.aspnetcore 0.4.14-beta available on NuGet.
