### ISSUE TITLE
Resolving deeply nested links to entries

### ISSUE THREAD

**Issue by dibble-james** [contentful/contentful.net#46]
When calling `IContentfulClient.GetEntriesAsync<T>` and using a `Include(int)` greater than the default of 1, I was expecting my references to be resolved into my object graph to that level also.

Say I have a Content Model like:
```
ContentTypeA
- String Field

ContentTypeB
- References Many ContentTypeA
- Another String Field

ContentTypeC
- References a Single ContentTypeA

ContentTypeD
- References Many ContentTypeB
- References Many ContentTYpeC
```

With corresponding POCOs like:
```csharp
public class ContentTypeA
{
   public string Field { get; set; }
   public SystemProperties Sys { get; set; }
}

public class ContentTypeB
{
   public List<ContentTypeA> ContentTypeA { get; set; }   
   public string AnotherField { get; set; }
   public SystemProperties Sys { get; set; }
}

public class ContentTypeC
{
   public ContentTypeA ContentTypeA { get; set; } 
   public SystemProperties Sys { get; set; }
}

public class ContentTypeD
{
   public List<ContentTypeB> ContentTypeB { get; set; }   
   public List<ContentTypeC> ContentTypeC { get; set; }
   public SystemProperties Sys { get; set; }
}      
```

And then I call `IContentfulClient.GetEntiresAsync<ContentTypeD>` I get a list of `ContentTypeD`s where all my list properties are populated and the `ContentTypeB.AnotherField` property is populated too, but the list of `ContentTypeA`s on the `ContentTypeB`s have their `Sys.Type` properties containing `Link` with `null` for the `ContentTypeA.Field`.

If I use `IContentfulClient.GetEntriesCollectionAsync` all the linked and expected `ContentTypeA`s are on the `ContentfulCollection.IncludedEntries`, but the same behaviour is observed.  

So, the question/issue is, should I be resolving those links myself or has this scenario not been baked into the client yet but is the expected behaviour when you've got out of beta?

**Comment by Roblinde** [comment]
Hi!

The intention is definitely that this should work. I just resolved another issue with a similar problem just a week or so back. What version of the SDK are you using?

**Comment by dibble-james** [comment]
We were on `0.10.0-beta`.  I've just updated to `0.11.1-beta` but it only seems to work if I wrap my objects with `Entry<T>`.  Eg:
```csharp
public class ContentTypeD
{
   public List<Entry<ContentTypeB>> ContentTypeB { get; set; }   
   public List<Entry<ContentTypeC>> ContentTypeC { get; set; }
   public SystemProperties Sys { get; set; }
}     
```

**Comment by Roblinde** [comment]
Hmm, that is weird that should have no implication. Does your classes by any chance implement the `IContentfulResource` interface?

**Comment by Roblinde** [comment]
No, not at all. Plain POCOs are fine. But if you _had_ implemented `IContentfulResource` I could understand the difference in deserialization, but you shouldn't 😄 

Ok, so this is certainly strange, if it works with `Entry<T>` it should definitely work with `T` directly as well. 
Sounds like there is something going wrong in the deserialization. What the SDK does to allow you to use POCOs directly is to alter the structure of the returned JSON slightly. Might be something there that goes awry, but it's strange because there are tests covering this scenario.

Could you possibly share a JSON response from Contentful? Be careful to remove any sensitive information. And I'll try it on my end and see if I can work out what's going on.

**Comment by dibble-james** [comment]
Sure, take a look at this: https://gist.github.com/dibble-james/941a8f2a8e5333ed7119d9fe2c1b24e3

**Comment by Roblinde** [comment]
Perfect! I'll have a look asap.

**Comment by Roblinde** [comment]
This is unfortunately a very unhelpful response, but it works fine for me.

I'm running a test with these POCO classes:

```csharp
public class Page
    {
        public string Name { get; set; }
        public string PageTitle { get; set; }
        public List<Button> Buttons { get; set; }
        public List<InputField> InputFields { get; set; }
        public List<Label> Labels { get; set; }
        public ContentTypeE ContentTypeE { get; set; }
    }

    public class NestedPage {
        public string Term { get; set; }
    }

    public class Button
    {
        public string Name { get; set; }
        public NestedPage Text { get; set; }
    }

    public class InputField
    {
        public string Name { get; set; }
        public NestedPage ContentTypeF { get; set; }
    }

    public class Label
    {
        public string Name { get; set; }
        public NestedPage Content { get; set; }
    }

    public class ContentTypeE
    {
        public string Name { get; set; }
        public string Content { get; set; }
    }
```

And everything seems to be serialized fine. 

Is there anything else we're missing here? How does your classes look exactly? Maybe we can discover something if I run with identical classes.

**Comment by dibble-james** [comment]
Property names withstanding, our classes look identical.

I'm using:
```csharp
 var pages = await this.contentful
                .GetEntriesAsync(QueryBuilder<Entry<ContentTypeModels.Page>>.New.Include(10).Limit(1000).ContentTypeIs(ContentTypeModels.Page.ContentTypeId))
                .ConfigureAwait(false);
```

**Comment by Roblinde** [comment]
Aha, and if you go like this instead:

```csharp
var pages = await this.contentful .GetEntriesAsync(QueryBuilder<ContentTypeModels.Page>.New.Include(10).Limit(1000).ContentTypeIs(ContentTypeModels.Page.ContentTypeId))
                .ConfigureAwait(false);
```
(Remove the `Entry<T>` wrapper from the QueryBuilder)

I believe you'll find that everything works as expected. 

If you need the systemproperties you should be able to just add a property like this to each class `public SystemProperties Sys { get; set; }`

The reason this fails when wrapping in `Entry<T>` is because then the deserialization assumes that all of your entities will be wrapped this way (which incidentally is also why it works when you wrap them), this is just an oversight on my part. I believe it's more convinient anyway to use the plain class directly, right?

I notice that you're using `.ConfigureAwait(false)` which is fine, but just FYI that's also being done throughout the SDK so you _should_ not need to do that on your side, but it's better to be safe than sorry I guess 😄

**Comment by dibble-james** [comment]
Yes, it is definitely easier to have the plain classes.  

I get the same results though, although in a slightly different guise; the references of a reference `Sys` properties are now populated as entries, not links, but their properties are null. Eg,  The `Label.Content` and `Label.Name` are null when a `Label` is referenced by a `InputField` from a `Page`.  (Can you see what we're trying to do with Contentful by any chance?)

That's good to hear about the `ConfigureAwait`.  As you say, policy here is to always use it on 3rd party APIs to be safe.  Your SDK isn't the only one we consume and you never know who's done their homework on `async/await` 😉.

**Comment by Roblinde** [comment]
Argh, I really thought we had this one now. Ok, so lets see.You get populated objects, but all properties are null... And you're not doing any `Entry<T>` properties anywhere? This makes me even more bewildered...

And your structure is Page -> Labels -> Content and both the label properties and the content is null?

**Comment by dibble-james** [comment]
Yeah, it really felt like this was close.  No `Entry<T>` on the POCOs or when calling the SDK.

The structure is:
```
Page
- Input Fields[]
-- Name (free text)
-- Label
--- Name (free text)
--- Content
---- Term (free text)
```
So `Page -> Input Field[0].Name` has a value, `Page -> Input Field[0] -> Label.Name` is null and `Page -> Input Field[0] -> Label -> Content` is null so I can't get at `Term`.

I appreciate we've strayed into support territory here so thanks for the help 😄.  If you're feeling at a brick wall I'm happy to dig into this myself and raise a PR?

**Comment by Roblinde** [comment]
No problem at all. This SDK is my baby and I want it working as cleanly and smoothly as possible.

That said, a PR is of course always welcome if you find something.

It's weird though, here's the test I run with my classes and your json response (I've added the "tada"):

`Assert.Equal("tada", list[0].Labels[0].Content.Term);`

This passes just fine.

I'll keep looking around a little bit to see if I can find anything else. Let me know if you make any progress.

**Comment by dibble-james** [comment]
I created a test for myself and spotted the issue immediately when looping through `ContentfulClient.ResolveLinks`.  My POCO didn't match the naming on the Content Model _exactly_ (ie a typo...) so when JSON.Net tried to deserialize the linked object the properties were null.  😞.  

Cheers again for your help.

**Comment by Roblinde** [comment]
Lovely! Then all is good in Contentful land.

Good luck with the project and just let me know if I can be of service or if you spot any peculiarities.

Cheers!
