### ISSUE TITLE
GetEntriesAsync not always working after recent id/ref change

### ISSUE THREAD

**Issue by aKzenT** [contentful/contentful.net#47]
The new deserialization logic using $id/$ref has a flaw that makes the deserialization fail in some cases when there are multiple link-properties on the same entity.

The fault is in the ResolveLinks method which iterates through the properties in reverse order. This results in a JSON that can have a $ref before the corresponding $id.

The fix seems to be simply to reverse the iteration order.

I will attach a pull request with the fix and a test case shortly.

**Comment by aKzenT** [comment]
Please see the pull request #48.

While doing test unfortunately I found another bug with the AssetJsonConverter which the PR should fix as well. Basically the problem is that as soon as you are using a customer JSON converter, you are completely responsible for how to deserialize your objects. So things like reference handling has to be done manually if required. In the test case there are two links to the same asset. The second one will use $ref internally, but since assets are using the special converter, JSON.NET will not resolve the $ref automatically and still calls the ReadJson method.

See also: https://github.com/JamesNK/Newtonsoft.Json/issues/1236

The easiest solution for now is to manually resolve and add references in the converter.

**Comment by Roblinde** [comment]
Great find!

I'm out of office for the week, will be back again on Thursday next week, but I'll see if I can find some time to review this before then.

**Comment by aKzenT** [comment]
That would be awesome!

**Comment by Roblinde** [comment]
Merged and new version available on NuGet. Many thanks for the contribution and just let me know if I can be of any further assistance!
