### ISSUE TITLE
There is no way of paging through ContentfulManagementClient::GetAssetsCollectionAsync

### ISSUE THREAD

**Issue by matt-hammond** [contentful/contentful.net#49]
GetAssetsCollectionAsync returns the top 100 row, but does not take a QueryBuilder/queryString so it is not possible to either specify a higher limit or page through the result set.

**Comment by Roblinde** [comment]
That's a huge oversight on my part. I have a new package version planned for Thursday. I'll fix this for that as well. 

Thanks for finding it!

**Comment by matt-hammond** [comment]
No worries, many thanks.

**Comment by Roblinde** [comment]
This should now be resolved in the latest version 0.12.0-beta. 🎉 

Let me know if something is still amiss.
