### ISSUE TITLE
Allow custom JsonSerializerSettings inside the client

### ISSUE THREAD

**Issue by aKzenT** [contentful/contentful.net#51]
Currently all calls to JSON.NET within the library seem to use the default overloads which use the default JsonSerializerSettings.

Currently the only way to customize the deserialization process for contentful is to change the default serialization setings for JSON.NET (e.g. custom converters, $id/$ref support, etc.).

In our application we have lots of components and libraries which use JSON.NET for serialization and deserialization, so changing the default settings affects all of these as well.

It would be nice if contentful.net would support supplying custom SerializerSettings.

**Comment by Roblinde** [comment]
Excellent suggestion!

In your opinion, should this on a per call, per client or a global setting?

A few options spring to mind.

1. Make it part of the ContentfulOptions passed in when creating the client.
2. Make it a property on the client that needs to be set before/after each request. 
3. Add settings as an overload to each request.

**Comment by aKzenT** [comment]
I think you should expose this on the constructor and/or as a property on the client. Having separate overloads would be too much in my opinion. Especially because you can always use multiple instances of the client itself, if you have different needs in different parts of your application.

**Comment by aKzenT** [comment]
Thinking about it, using a property could make the most sense as you can then preset the settings to a sensible default for contentful (e.g. adding AssetJsonConverter, etc.). Using the ContentfulOptions could then be an additional way in order to easily support the configuration framework in mvc.

**Comment by Roblinde** [comment]
Sounds reasonable, I'll look into it.

**Comment by aKzenT** [comment]
Please see submitted PR

**Comment by Roblinde** [comment]
Again, thanks for the contributions! This is now in the latest version on NuGet.
