### ISSUE TITLE
MimeTypeValidator doesn't create expected Json object

### ISSUE THREAD

**Issue by mercedesb** [contentful/contentful.net#56]
Currently when using the MimeTypeValidator on a field in content type creation via code, the validation is added to the field but the mime type is not selected.

In CreateValidator(), the code should be changed from
`  return new { linkMimetypeGroup = MimeTypes.Select(c => c.ToString()), message = Message };`
to
` return new { linkMimetypeGroup = MimeTypes.Select(c => c.ToString().ToLower()), message = Message };`

**Comment by Roblinde** [comment]
Thanks, you're quite right! I'll get that fixed.

**Comment by Roblinde** [comment]
A new package is now available that should fix this. Let me know if it doesn't work as you'd expect.

Thanks for the contribution.

Cheers!
