### ISSUE TITLE
QueryBuilder.FieldEquals forces all field IDs to camelCase

### ISSUE THREAD

**Issue by rytmis** [contentful/contentful.net#62]
Given that the Contentful web interface allows for e.g. PascalCase field identifiers, it seems a bit weird to force the property names to camelCase in the Query Builder, as this leads to failing queries. This happens regardless of whether one specifies a `[JsonPropertyAttribute]` on the property in question.

A workaround is to use `FieldEquals($"field.{nameof(ClassName.PropertyName)}", value)`.

**Comment by Roblinde** [comment]
Ah yeah, that's true.

Probably it should just go camelCase if there's no `JsonPropertyAttribute`, it seems reasonable to default to this if no other information is given. Do you agree?

**Comment by rytmis** [comment]
Seems reasonable, yes, given how the web interface defaults to camelCase. 

Also, I dug through the sources to find out that it does in fact support JsonPropertyAttribute -- if that _is_ documented somewhere, I wasn't smart enough to find it. :)

Mind you, that would obviously be a breaking change for anyone already relying on JsonPropertyAttribute -- although since you're not yet at 1.x, that's not a SemVer violation in my understanding. :)

**Comment by Roblinde** [comment]
Yeah it does support the JsonPropertyAttribute, but it also makes it lower case unfortunately so that's not much help, but I could easily change that.

Yeah, one of the benefits of staying in beta 😛

**Comment by Roblinde** [comment]
I've looked at it some more now, and I really feel like this is a bug. It should of course respect the JsonProperty. I will try to get a fix out as soon as possible.

**Comment by Roblinde** [comment]
This should now be resolved in the latest version. Unfortunately this means you'll have to put `[JsonProperty]` attributes on your properties that does not have camel casing in Contentful which is kinda sad, but I'm afraid we'll have to live with that.

Let me know if something seems strange.

Thanks!

**Comment by rytmis** [comment]
Awesome, thanks a lot!
