### ISSUE TITLE
CDA/CMA GetEntriesAsync for Entry<> doesn't resolve the includes

### ISSUE THREAD

**Issue by mercedesb** [contentful/contentful.net#70]
When using `GetEntriesAsync<Entry<ContentType>>` the includes are not resolved, but `GetEntriesAsync<ContentType>` does correctly resolve the includes.

This was happening with a field of type Array of references (not sure if it also happens for a singular reference).

**Comment by Roblinde** [comment]
Yeah, we did have that. Think that was resolved in version 0.13.2-beta, which version are you running?

Hope it's not something that's come back 😱

**Comment by Roblinde** [comment]
You can see the other discussion here: #64

**Comment by mercedesb** [comment]
I'm using 0.13.5-beta

**Comment by mercedesb** [comment]
Reading through the referenced issue, I can just add Sys to all of my POCO objects (I already do, but thought Entry<> was the way it was supposed to be done :) ) 

I definitely need the SystemProperties object throughout the code and across use cases, but it makes no difference how I access it.

**Comment by Roblinde** [comment]
Yeah, Sys to the POCOs is better all around probably. I'd still like to understand what goes wrong in the deserialization of `Entry<T>` though. 

Are all of the referenced entries in the array null?

Do you happen to have a json response I could look at? Keep in mind to remove sensitive data.

I'll see if I can replicate and fix the issue.

**Comment by mercedesb** [comment]
Here's the JSON serialized object I get back from ContentfulClient.GetEntriesAsync<Entry<Room>> (it's just a little room reservation app in order to play with Contentful features)

`{
	"sys": {
		"Id": "5dDVhwkIIwSyMU6S8YQ2So",
		"LinkType": null,
		"Type": "Entry",
		"Revision": 2,
		"Version": null,
		"CreatedAt": "2017-05-15T22:21:28.023Z",
		"CreatedBy": null,
		"UpdatedAt": "2017-05-15T22:25:33.345Z",
		"UpdatedBy": null,
		"DeletedAt": null,
		"Locale": "en-US",
		"ContentType": {
			"sys": {
				"Id": "makingWavesRoom",
				"LinkType": "ContentType",
				"Type": "Link",
				"Revision": null,
				"Version": null,
				"CreatedAt": null,
				"CreatedBy": null,
				"UpdatedAt": null,
				"UpdatedBy": null,
				"DeletedAt": null,
				"Locale": null,
				"ContentType": null,
				"Space": null
			},
			"Name": null,
			"Description": null,
			"DisplayField": null,
			"Fields": null
		},
		"Space": {
			"sys": {
				"Id": "ded68waj6yma",
				"LinkType": "Space",
				"Type": "Link",
				"Revision": null,
				"Version": null,
				"CreatedAt": null,
				"CreatedBy": null,
				"UpdatedAt": null,
				"UpdatedBy": null,
				"DeletedAt": null,
				"Locale": null,
				"ContentType": null,
				"Space": null
			},
			"Name": null,
			"Locales": null
		}
	},
	"Fields": {
		"Name": "Fishbowl",
		"Seats": 6,
		"HasTable": true,
		"HasAppleTV": true,
		"AppleTVName ": "Apple TV ",
		"HasChromecast": false,
		"HasConferencing": false,
		"Reservations": [{
			"reservedBy": null,
			"subject": null,
			"start": null,
			"end": null,
			"Sys": {
				"Id": "5WsriOlrEWgMasOe6gSuEM",
				"LinkType": null,
				"Type": "Entry",
				"Revision": 1,
				"Version": null,
				"CreatedAt": "2017-05-15T22:23:43.122Z",
				"CreatedBy": null,
				"UpdatedAt": "2017-05-15T22:23:43.122Z",
				"UpdatedBy": null,
				"DeletedAt": null,
				"Locale": "en-US",
				"ContentType": {
					"sys": {
						"Id": "RoomReservation",
						"LinkType": "ContentType",
						"Type": "Link",
						"Revision": null,
						"Version": null,
						"CreatedAt": null,
						"CreatedBy": null,
						"UpdatedAt": null,
						"UpdatedBy": null,
						"DeletedAt": null,
						"Locale": null,
						"ContentType": null,
						"Space": null
					},
					"Name": null,
					"Description": null,
					"DisplayField": null,
					"Fields": null
				},
				"Space": {
					"sys": {
						"Id": "ded68waj6yma",
						"LinkType": "Space",
						"Type": "Link",
						"Revision": null,
						"Version": null,
						"CreatedAt": null,
						"CreatedBy": null,
						"UpdatedAt": null,
						"UpdatedBy": null,
						"DeletedAt": null,
						"Locale": null,
						"ContentType ": null,
						"Space": null
					},
					"Name": null,
					"Locales": null
				}
			},
			"ContentTypeId": "RoomReservation",
			"ContentTypeName": null,
			"ContentTypeDescription": null
		}, {
			"reservedBy": null,
			"subject": null,
			"start": null,
			"end": null,
			"Sys": {
				"Id": "1Z7LYARFf6aY6kuW2OY6eG",
				"LinkType": null,
				"Type": "Entry",
				"Revision": 1,
				"Version": null,
				"CreatedAt": "2017-05-15T22:24:04.059Z",
				"CreatedBy": null,
				"UpdatedAt": "2017-05-15T22:24:04.059Z",
				"UpdatedBy": null,
				"DeletedAt": null,
				"Locale": "en-US",
				"ContentType": {
					"sys": {
						"Id": "RoomReservation",
						"LinkType": "ContentType",
						"Type": "Link",
						"Revision": null,
						"Version": null,
						"CreatedAt": null,
						"CreatedBy": null,
						"UpdatedAt": null,
						"UpdatedBy": null,
						"DeletedAt": null,
						"Locale": null,
						"ContentType": null,
						"Space": null
					},
					"Name": null,
					"Description": null,
					"DisplayField": null,
					"Fields": null
				},
				"Space": {
					"sys": {
						"Id": "ded68waj6yma",
						"LinkType": "Space",
						"Type": "Link",
						"Revision": null,
						"Version": null,
						"CreatedAt": null,
						"CreatedBy": null,
						"UpdatedAt ": null,
						"UpdatedBy": null,
						"DeletedAt": null,
						"Locale": null,
						"ContentType": null,
						"Space": null
					},
					"Name": null,
					"Locales": null
				}
			},
			"ContentTypeId": "RoomReservation",
			"ContentTypeName": null,
			"ContentTypeDescription": null
		}],
		"Sys": null,
		"ContentTypeId": "makingWavesRoom",
		"ContentTypeName": "RoomScheduler.Models.Room",
		"ContentTypeDescription": null
	}
}`

This may be unrelated so let me know if you want me to start another thread when I get to the office, but I'm seeing weird behavior when using the CMA's CreateOrUpdateEntry on the response from CMA GetEntriesAsync() if there are referenced entries (i.e. trying to add a reservation to a room's reservation list).  The documentation is a little off for that call so I'm not sure if what I'm seeing is expected or not.

**Comment by mercedesb** [comment]
Oops, I had that all formatted for you and lost it :( sorry

**Comment by Roblinde** [comment]
No problem, thanks for this. I'll see if I can replicate it and try to work out what's going wrong.

**Comment by Roblinde** [comment]
I think we should open a new issue for the CMA response things and dive into it there.

**Comment by Roblinde** [comment]
Ah, now I see. If you're using `Entry<T>` then it is expected that all references also. So your class would look something like:

```csharp
public class RoomReservation {
    public List<Entry<Reservation>> Reservations { get; set; }
}
```

But as we've already established, it's better to use a POCO all around 😄 

I'm actually looking at just scrapping `Entry<T>`, but not quite sure how to handle the management side of things if I do.

**Comment by mercedesb** [comment]
POCO it is :)
