### ISSUE TITLE
QueryBuilder dies with RuntimeBinderException on incorrect API key

### ISSUE THREAD

**Issue by jouniheikniemi** [contentful/contentful.net#71]
If I try to access a space with an invalid API key, the API returns 404. QueryBuilder doesn't handle this gracefully, but obviously tries to parse the result. That leaves me with stack traces of this sort (async frames removed):

`RuntimeBinderException: Cannot perform runtime binding on a null reference

CallSite.Target(Closure , CallSite , object )
System.Dynamic.UpdateDelegates.UpdateAndExecute1<T0, TRet>(CallSite site, T0 arg0)
Contentful.Core.ContentfulClientBase+<CreateExceptionForFailedRequestAsync>d__8.MoveNext()
Contentful.Core.ContentfulClientBase+<EnsureSuccessfulResultAsync>d__14.MoveNext()
Contentful.Core.ContentfulClientBase+<SendHttpRequestAsync>d__11.MoveNext()
Contentful.Core.ContentfulClientBase+<SendHttpRequestAsync>d__10.MoveNext()
Contentful.Core.ContentfulClient+<GetAsync>d__32.MoveNext()
Contentful.Core.ContentfulClient+<GetEntriesAsync>d__14.MoveNext()
Contentful.Core.ContentfulClient+<GetEntriesAsync>d__13.MoveNext()`

If I have an invalid API key, there's a graceful error message because it can't be converted to a bearer token, but a valid token for another space causes this.

**Comment by Roblinde** [comment]
Thank you, I'll look into it!

**Comment by Roblinde** [comment]
Hi, this should now be fixed in the latest version.

The problem was an inconsistensy in the error format in our API, there was no `error` object returned in the `details` object. I've made the code slightly more resilient to this case.

Thanks again for the report and let me know if it doesn't seem to work for you.
