### ISSUE TITLE
.NetCore support and release of package

### ISSUE THREAD

**Issue by pfrendo** [contentful/contentful.net#73]
I have seen that you have created a folder for .NetCore integration but I would also like to know if there are any plans to publish the nuget for it and continue working on it. Thanks

**Comment by pfrendo** [comment]
I have seen that you have a pre-release version, I'm trying it out :)

**Comment by Roblinde** [comment]
Leaving this here in case someone else wonders. We have two nuget packages currently.

contentful.csharp
contentful.aspnetcore

At the time of this writing they are still in pre-release and runs on netstandard 1.4 and netstandard 1.5 respectively.
