### ISSUE TITLE
Removing properties from QueryBuilder

### ISSUE THREAD

**Issue by davidmeekstockport** [contentful/contentful.net#80]
Hi Rob,

We are currently trying to recurse through calls of GetEntriesAsync with a different skip parameter to retrieve all the entries that are above our limit.

Every time we loop through we would like to change the Skip() property to a new value as to give us the correct batch of entries. However when we use .Skip(int) it is adding a new skip property on top and throwing an error when we have multiple. We are not able to create a copy of the builder then add skip to that because it is a reference.

Would it be possible to remove properties or clone the querybuilder object?

Thanks,

David

**Comment by Roblinde** [comment]
Hi David,

That sounds interesting. Could you provide me with a little code example so I'm sure I understand the issue correctly?

I'm out travelling most of today, but will have a look when I get a minute.

Cheers

**Comment by davidmeekstockport** [comment]
Hi Rob,

This is the full method:


```
public async Task<IEnumerable<T>> GetEntriesAsync<T>(QueryBuilder<T> queryBuilder, int batchNumber = 0, List<T> fullListEntries = null, CancellationToken cancellationToken = default(CancellationToken))
        {
            if (fullListEntries == null)
            {
                fullListEntries = new List<T>();
            }

            var queryBuilderWithSkip = queryBuilder;

            var entries = await _client.GetEntriesAsync(queryBuilder, cancellationToken);

            fullListEntries.AddRange(entries);

            if (entries.Count() == 5)
            {
                batchNumber++;
                queryBuilderWithSkip.Skip(5 * batchNumber);              
                await GetEntriesAsync(queryBuilder, batchNumber, fullListEntries, cancellationToken);              
            }
            
            return fullListEntries;
        }

```

I have used 5 as the limit for testing. So if it hits the limit of 5 it will call the same method again and skip the previous entries. There are a few possible issues/solutions I can see here.

- We could clone queryBuilder instead of pointing to it's reference, this would mean that queryBuilderWithSkip would have skip and queryBuilder wouldn't have it at all.

- We could remove the skip if it has it and add it back on with the new value

- When we call skip for a second time it replaces the current value that is set for it. 

I hope this makes sense!

Thanks,

David

**Comment by Roblinde** [comment]
Hi David

QueryStringBuilder is really nothing more than a glorified StringBuilder, what you could do is simply something like this: 

```csharp
public async Task<IEnumerable<T>> GetAllEntriesAsync<T>(QueryBuilder<T> queryBuilder, int batchNumber = 0, int batchSize = 5, CancellationToken cancellationToken = default(CancellationToken))
        {
            var entries = await _client.GetEntriesAsync<T>($"{queryBuilder.Build()}&skip={batchNumber * batchSize}", cancellationToken);

            if(entries.Count() == batchSize)
            {
                entries.Concat(await GetAllEntriesAsync(queryBuilder, batchNumber + batchSize, batchSize, cancellationToken));
            }

            return entries;
        }
```

Disclaimer: I haven't actually run the above code, but I think it should work.

**Comment by Roblinde** [comment]
Hi @davidmeekstockport 

Just wanted to make sure this solution helped you out.

I'll close the issue for now, but feel free to reopen it if you need anything further.

**Comment by davidmeekstockport** [comment]
Hi Robert,

Yep that fixed it, thanks! I had it in my mind that my last resort would be some sort of horrible regex replace. But this was much more obvious!

Thanks,

David
