### ISSUE TITLE
Missing or inaccessible entries should be skipped during deserialization

### ISSUE THREAD

**Issue by aKzenT** [contentful/contentful.net#81]
Currently, if you have a contentful entry that references another entity which no longer exists (e.g. was deleted). the deserialization routine will create an empty instance of the expected class.

For example, if you reference an asset and later delete the asset without updating its usages, you will get empty Asset-objects with all properties set to null. This can easily lead to bugs when code expects certain required properties to be filled. An example is the integrated ContentfulImageTagHelper which will throw a NullReferenceException if it encounters an Asset like this.

My suggestion is to skip such entries completely during deserialization, effectively converting them to "null" values, which makes them easier to handle in code.

**Comment by Roblinde** [comment]
Ah, interesting. Thanks! I will look into this. It's even plausible to contemplate whether or not they should be returned from the underlying Content Delivery API at all...

**Comment by aKzenT** [comment]
I send you a failing test case for the issue. I believe the test case should cover most cases as it includes Assets/normal entries and entries part of an array.

**Comment by aKzenT** [comment]
Okay, I believe I found an easy fix for the issue. Please see the updated PR. Basically if the include cannot be found, I just remove the node that referenced it.

Thanks for your quick responses!

**Comment by Roblinde** [comment]
Fantastic!

I'll review first chance I get.

There's one thing on my mind and that is when entries have links that are unable to be resolved they're actually added to a separate part of the API response like this:

```
"errors": [
    {
      "sys": {
        "id": "notResolvable",
        "type": "error"
      },
      "details": {
        "type": "Link",
        "linkType": "Asset",
        "id": "3aLduDq104aa0oYY4MmCmM"
      }
    },
    {
      "sys": {
        "id": "notResolvable",
        "type": "error"
      },
      "details": {
        "type": "Link",
        "linkType": "Entry",
        "id": "4UEXLRYoOkYooo8msg8CoU"
      }
    }
  ]
```

I'm considering just checking this array for the sys id and in that case removing the node otherwise leaving it there. This would give a difference between an item being deleted or unpublished and when you're simply not including enough levels of referenced entities with the `includes` parameter.

What do you think?

**Comment by aKzenT** [comment]
That's a very good point and probably needed in some use cases, so that you can retrieve the item using the id later (lazy loading). I haven't thought of that.

Would you like me to update the PR or are you going to make the necessary changes yourself?

The update would be quite useful for my current project, so if there is any way I can help to speed up the process, just let me know.

Thanks!

**Comment by Roblinde** [comment]
I'll have a look at it tomorrow. I'll let you know and we can collaborate on the details if necessary.

Thanks so far!

**Comment by Roblinde** [comment]
Added a new branch #85 that I'd love for you to test out. Still a little bit of work left, but if everything seems good we can probably get this out today. It includes some other refactors as well, consolidating the `ContentfulCollection` and making sure to get rid of the unintuitive `GetEntriesCollectAsync` methods.

**Comment by aKzenT** [comment]
Hey,

I just tested a few scenarios with the new version and everythhing seems to work just as expected.

I'm going to review the code changes as well later today to see if I notice anything else.

Thanks!

**Comment by Roblinde** [comment]
Excellent!

I've got it lined up and ready to be merged and released.

**Comment by aKzenT** [comment]
Hey,

I don't see any issues with the code. During my tests I discovered another deserialization bug in the old version when you have 2 links to the same deleted asset (would cause duplicate id error in JSON.NET). This also seems to be fixed now.

Unifying the GetEntries* methods is a good idea as well in my eyes.

One improvement could be to add the source entity that caused the missing link to the error information, since that information is lost now. But this is not something we need at the moment and could be added at a later time if needed.

Thanks!

**Comment by Roblinde** [comment]
Yeah, agree it would be a good idea to add the source entity. I'll release this and open a new issue to track that.

Thanks for all the contributions.
