### ISSUE TITLE
Can you merge properties by default locale?

### ISSUE THREAD

**Issue by pfrendo** [contentful/contentful.net#84]
I would like a way to merge properties with a default locale.

My scenario is the following:

```
TestContentType (English-Default)
{
Name: "Test",
Surname: "Test-English"
}

TestContentType (German)
{
Name: null,
Surname: "Test-German"
}
```

When I request german I would like this model to be returned
```
TestContentType (German)
{
Name: "Test",
Surname: "Test-German"
}
```

Now this can either be achieved by handling it within the SDK or by allowing me to query multiple locales at the same time... as currently I can only query one locale.

So I can use something like this
```
new QueryBuilder<T>().ContentTypeIs(contentType).LocalesAre(new List<string>() { defaultLocale, locale });
```

**Comment by pfrendo** [comment]
Have set the ```fallbackCode``` I think it will do for now :)

Although a multi locale query would be cool but as far as I can see it's a limitation from contentful

**Comment by Roblinde** [comment]
Was just about to say, fallback locales should sort you out with this hopefully 😄

**Comment by Roblinde** [comment]
You can make multi locale queries as well, but you can only request *all* locales. Just specify `*` as your locale. This returns all locales but also alters the JSON structure.

The returned result looks something like this:

```
{
sys: { //sys properties},
fields: {
    name: {
        'en-US': "Test",
        'de-DE': "Test-german"
    }
  }
}
```

Which means you'd have to wrap all the properties of your model in dictionaries. Something like:

```
public class TestContentType {
     public Dictionary<string, string> Name { get; set; }
}
```

And then access the value like so:

```
var englishName = type.Name["en-Us"];
```

**Comment by pfrendo** [comment]
Yep but I would prefer to avoid that as it would be a big load for the application and would effect site speed. I only call the locale I need and then on update I handle all locales (webhook) ... Thanks for the swift reply btw :D

**Comment by Roblinde** [comment]
I agree, I avoid `locale=*` if I can. 😄 

Just let me know if you need anything else.
