### ISSUE TITLE
Using this SDK in ASP.NET Framework 4.5

### ISSUE THREAD

**Issue by chengkiang** [contentful/contentful.net#86]
We have an existing project on ASP.NET Framework 4.5, how can we make use of this SDK, which is on ASP.Net Core? Alternatively, is there a version which targets .NET 4.5?

**Comment by Roblinde** [comment]
Hi @chengkiang 

There is no SDK targeting Framework 4.5, but it can be used with 4.6.1 as it targets netstandard 1.5

So if you have the possibility to upgrade to 4.6.1 everything will work as expected.

Hope this helps.
