### ISSUE TITLE
Any plans on making .net 4.6 library?

### ISSUE THREAD

**Issue by Woland2k** [contentful/contentful.net#89]
.NET Core is still quite new and lacks support from other products/libraries. Do you plan to have .net 4.6 library available?

**Comment by Roblinde** [comment]
Hi Woland

The library targets NetStandard 1.4 This means that you can use it from a full framework project that targets .NET 4.6.1 and above. Just install it as you would any other NuGet package.

We do not currently have any plans to support anything below NetStandard 1.4

Hope this helps.

**Comment by Woland2k** [comment]
It installed a lot of .net core dependencies, thanks anyway.
