### ISSUE TITLE
Did format changed for fields property?

### ISSUE THREAD

**Issue by Woland2k** [contentful/contentful.net#90]
In your json files it is:
```
...
  "fields": {
    "productName": "SoSo Wall Clock",
    "slug": "soso-wall-clock",
...
```
but when I request entry now, it is more like this:
```
...
  "fields": {
    "productName": {
      "en-US": "SoSo Wall Clock"
    }
...
```
This complicates parsing json quite a bit in .net

**Comment by Roblinde** [comment]
Hi Woland

There are unfortunately two different formats. One if you request all locales with `locale=*` or fetch your content from the Content Management API. This is the format you see which includes the language keys (`en-US` for example).

If you make a request for a single locale (or without specifying locale) from the Content Delivery API however the format will be without language keys as in your first example.

You can read more about localization here: https://www.contentful.com/developers/docs/references/content-delivery-api/#/reference/localization

Hope this helps.

**Comment by Woland2k** [comment]
I'm more concerned about web hooks, is there way to control it for those?

**Comment by Roblinde** [comment]
Ah yes, web hooks always return all of the locales which means it will always return your entry with the `en-US` key. 

It's a bit annoying but a way to model it would be to create a class similar to this:

```
public class Person {
   public Dictionary<string, int> Age { get; set; }
   public Dictionary<string, string> Name { get; set; }
}
```

Then it would deserialize correctly and you could retrieve the values something like this:

```
var p = GetPersonFromWebHook();

var age = p.Age["en-US"];
var name = p.Name["en-US"]
```

**Comment by Woland2k** [comment]
Thanks for the info, this is how I created my classes.
