### ISSUE TITLE
ResolveLinks throws NullReferenceException when select is used in query

### ISSUE THREAD

**Issue by rangp** [contentful/contentful.net#91]
The method `ResolveLinks` in the `ContentfulClient` throws whenever a select is used in a query string, because in that case the Contentful API doesn't return the `sys.id` property but only the fields that have been selected. Thus in line 267

`            var id = ((JValue) entryToken.SelectToken("$.sys.id")).Value.ToString();
            entryToken.AddFirst(new JProperty( "$id", new JValue(id)));`

throws a NullReferenceException. 

It's hard to include an example without a proper contentful API connection but I hope you're able to reproduce this. Makes using the new contentful.aspnetcore package impossible for me at this point.

Example query string: `?include=2&content_type=mytype&order=-sys.updatedAt&select=fields.myfield`

Cheers
Peter

**Comment by Roblinde** [comment]
Hi Peter

Good catch, I'll make that more resilient.

In the mean time you can include the `sys.id` field in your query and everything should work again.

For example: `?include=2&content_type=mytype&order=-sys.updatedAt&select=fields.myfield,sys.id`

Hope this helps!

**Comment by Roblinde** [comment]
Good morning, there's now a new package available that should resolve this issue for you.

Feel free to update and try it out.

Thanks for your contribution.

**Comment by rangp** [comment]
Looks good, thank you!
