### ISSUE TITLE
Start targeting .NET Standard 2.0

### ISSUE THREAD

**Issue by olegburov** [contentful/contentful.net#98]
So, [.NET Standard 2.0 ](https://blogs.msdn.microsoft.com/dotnet/2017/08/14/announcing-net-standard-2-0/) has been release with a wide support by different frameworks (.NET Core 2.0, .NET Framework 4.6.1, Mono 5.4, Xamarin and UWP later this year). The full list can be found [here](https://github.com/dotnet/standard/blob/master/docs/versions.md).

I think it's time to upgrade the project and start targeting .NET Standard 2.0 instead of 1.4.

**Comment by Roblinde** [comment]
I disagree, NetStandard 1.4 is superior!

Just kidding! An updated version targeting 2.0 was just released to NuGet.

Cheers!

**Comment by olegburov** [comment]
Awesome!

Just for the record, the NuGet package is here: https://www.nuget.org/packages/contentful.csharp/1.0.0
