### ISSUE TITLE
Migrate from ASP.NET Core 1.x to ASP.NET Core 2.0

### ISSUE THREAD

**Issue by olegburov** [contentful/contentful.net#99]
[ASP.NET Core 2.0](https://blogs.msdn.microsoft.com/webdev/2017/08/14/announcing-asp-net-core-2-0/) has been released. Therefore, it would be nice to upgrade the `Contentful.AspNetCore` project and start utilizing new features.

You can find details on how to migrate from ASP.NET Core 1.x to ASP.NET Core 2.0 [here](https://docs.microsoft.com/en-us/aspnet/core/migration/1x-to-2x/).

**Comment by Roblinde** [comment]
An updated package was just released to NuGet.
